### ISSUE TITLE
Список задач для автопилота

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#1]
сформировать issue для тех режимов которые не реализованы

**Comment by ponemetski** [comment]
PitchState
- [ ] Off
- [ ] VS
- [ ] AltAcq
- [ ] AltHold
- [ ] McpSpeed
- [ ] GS
- [ ] Toga
- [ ] VnavPath
- [ ] VnavSpeed
- [ ] Flare
- [ ] GA

**Comment by ponemetski** [comment]
RollState
- [] Off
- [] HdgSel
- [] Loc
- [] Vor
- [] Lnav
- [] GaTrack
- [] WingLevel

**Comment by ponemetski** [comment]
AtState
- [ ] Off
- [ ] Armed
- [ ] N1
- [ ] McpSpeed
- [ ] FmcSpeed
- [ ] ThrHld
- [ ] Retard

**Comment by ponemetski** [comment]
![2017-10-29 14 57 27](https://user-images.githubusercontent.com/1931079/32143389-886b561a-bcb9-11e7-9417-93a45d2099df.jpg)

**Comment by soitanen** [comment]
- [ ] Придумать возможность поворота самолета к заданному курсу не по кратчайшему расстоянию, а по направлению вращения задатчика курса (для возможности осуществления поворотов более чем на 180 градусов)
