### ISSUE TITLE
Список доработок по Upper EICAS

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#10]
- [x] расчет и вывод ограничения по оборотам на разных режимах
> Зеленые метки на шкале двигателей должны соответствовать текущему лимиту тяги. Плюс нужен правильный расчет взлетного лимита в CDU на странице N1 LIMIT.
- [x] объем топлива д.б. в килограммах, а не фунтах
- [x] не работают амбер надписи связанные с топливом
- [x] TAT должна выводиться всегда со знаком
- [x] не выводится расход топлива
- нет компактного режима дисплея, где в текстовом варианте пишутся N2, давление масла и т.п. #49

**Comment by soitanen** [comment]
Хорошая картинка с крупным видом на индиакцию N1. Видно, какая должна быть зеленая галочка и насколько сильно должна торчать стрелочка текущих оборотов.
![image](https://user-images.githubusercontent.com/2819664/33200554-2cf2f98a-d106-11e7-8a3d-a51194582c88.png)

**Comment by ponemetski** [comment]
R-TO - два варианта уменьшения тяги
вопросы
1) фиксированный дерейт
2) уменьшение по температуре 
3) совмещение этих двух методов

**Comment by soitanen** [comment]
По режимам. Вроде как когда только пришли на самолет и подали питание - режим получается --- (три тире). Т.е. он еще не посчитан. В реальном самолете даже автомат тяги в таком случае на земле сразу отключается. Потом мы вводим на странице N1 Limit температуру за бортом, выбираем мнимую температуру если надо и/или выбираем фиксированный дерейт. Тогда режим ограничения оборотов меняется на TO (в старых прошивках только так), в новых уже может быть D-TO, D-TO +55C... и так далее. Взлетели. Либо на высоте автоматического уменьшения тяги (она на второй страничке в закладке Takeoff), либо по ручному надатию на кнопку N1 на МСР - режим меняется на CLB. Когда достигли высоты полета, указанной в правом верхнем поле странички PERF INIT - меняется на CRZ. CRZ держится до самого захода на посадку. Когда активруется захват курсового и глиссадного маяков - активируется лимит G/A. Если отключаем автомат тяги - ничего не пропадает, метки остаются. Дальше предположения. Если жмем ТОГА и уходим на второй круг, то переход из лимита G/A в лимит CRZ скорее всего произойдет по активации в тангаже режима ALT ACQ или ALT HOLD. Хотя, возможно, что вообще по выходу из режиа TOGA в тангаже на любой другой.
Автомат тяги, соответственно, в любой момент времени своей работы не будет пытаться делать обороты выше лимита.

**Comment by soitanen** [comment]
Еще хорошая картинка
![image](https://user-images.githubusercontent.com/2819664/46944829-c9ccd800-d07b-11e8-9f97-18c123d6bad8.png)

**Comment by ponemetski** [comment]
> If CLB–1 or CLB–2 is selected, the N1% for CLB and the N1 cursors still display
values for full rated climb.

> clb1 делает обороты на 3% N1 меньше чем по таблице CLB, clb2 - на 6

> т.е. есть таблица CLB. Если выбрали дерейт в наборе, то до 10 футов он равен 3 или 6 процентам, к 30000 он линейно до 0 уменьшается, просто в процессе набора и сам CLB будет увеличиваться

**Comment by ponemetski** [comment]
> Либо на высоте автоматического уменьшения тяги (она на второй страничке в закладке Takeoff), либо по ручному нажатию на кнопку N1 на МСР - режим меняется на CLB. 

```
      TAKEOFF REF   2/2 
 RW WIND        RW COND 
---°/---   DRY/WET/SK-R>
 RW SLOPE/HDG    SEL/OAT
--.-%/---°   +55°/ +13°C
 TAKEOFF REF  CUTBACK N1
<QFE/QNH      80.5/ 80.5
 ACCEL HT    EO ACCEL HT
1000AGL          1000AGL
          THR  REDUCTION
          CLB     800AGL
-----------------CUTBACK
<INDEX            ON/OFF
```

а как именно называется высота автоматического уменьшения тяги?

**Comment by ponemetski** [comment]
> у нас сделано правильно - лампа Н1 не загорается при этом сценарии. У нас не сделано дургое при этом сценарии - обе лампы МАСТЕР над тумблерами директоров должны гореть (если включены) до момента переключения режима тангажа из ТОГИ во что-то другое, а потом остается только мастер.

сделал

**Comment by soitanen** [comment]
обороты считать научились, галки двигаем правильно. что еще обнаружил - есть самолеты где величина лимита выводится в процентах целеным цветом, есть где не выводится. И дальнейшее изучение документов говорит о том, что если мы имитируем что самолет умеет писать сложные вещи типа D-TO 1 +54, то он должен и эти зеленые циферки писать. вот выдержка из ФКОМ - when N1 SET outer knob is in AUTO position, may indicate fixed
derate, assumed temperature derate, or a combination of fixed and
assumed temperature derate
Not Displayed when Reverse Thrust is selected.
ну при реверсе понятно - там надпись REV

**Comment by soitanen** [comment]
В этом issue два скрина, второй как раз с цифрами - над фактическими
оборотами зелёные лимиты.

чт, 25 окт. 2018 г., 23:24 ponemetski <notifications@github.com>:

**Comment by soitanen** [comment]
еще нашел скрин интересный - самолет перед полетом. в расчетных оборотах - тире. хотя зеленые галки при этом что-то показывают (видимо рассчитаный на посадке до этого режим GA)
![image](https://user-images.githubusercontent.com/2819664/47913352-d68b6180-deac-11e8-9f32-fb5ee97ec938.png)

**Comment by ponemetski** [comment]
1) будем такое делать?
2) в остальном по этой issue все нормально? сейчас вспоминаю - вроде не готовы зеленые цифры лимита

**Comment by soitanen** [comment]
1 и 2 - ну да, я как раз и написал, потому что у нас цифры еще не сделаны -
можно сделать сразу правильно. Я понял логику этих зеленых галок - они как
будто двигаются по команде. т.е. если есть новые расчетные обороты -
двигаются к ним. расчет не ведется и там тире - стоят на каком-то старом
месте. Получается если сверху режим три тире, то обороты тоже будут тире.
Есть, конечно, еще экзотический режим где галки можно двигать вручную, но
он нам пока 100% не нужен.

пт, 2 нояб. 2018 г. в 19:10, ponemetski <notifications@github.com>:

**Comment by ponemetski** [comment]
готово, можно проверять

**Comment by soitanen** [comment]
галки вижу, как и было раньше, оборотов зеленых не вижу... я.диск обновлен
