### ISSUE TITLE
CDU LEGS

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#102]
- [x] Криво перестраивает маршрут - не так вставляет точки при спрямлении.
- [x] Не дает отменить выбранные изменения. Ты например берешь переставляешь, видишь пунктиром маршрут, а в левом нижнем сроке ЦДУ должно появиться <ERASE. А также если ты просто выскочишь в другую страницу, то изменения сотрутся, должны точнее. Сейчас у нас никак не отказаться от этих изменений.
- [x] курс до ближайшей точки не пересчитывается в режиме лнав
- когд аделаешь спрямление на точку, то справа внизу перед нажатием EXEC появляется надпись INTCP CRS (короче курс захвата или как-то так там написано). В чем суть - что к точке хоти подлететь не по прямой, а по конкретному радиалу. это страница 1478 в ФКОМе #141
- [x] теперь маска отображения точек маршрута совпадает с маской отображения линий

**Comment by ponemetski** [comment]
то что на видео не воспроизводится, может из за того что я выбрал аппроуч ILS28L

**Comment by ponemetski** [comment]
еще я все это тестирую не в режиме lnav

**Comment by ponemetski** [comment]
+ по возможности скажи плиз на каких страницах еще нужен ERASE

**Comment by soitanen** [comment]
ну у меня на том видео был выбран именно 28Л ИЛС заход, условия похожие... Но глюка какая-то явно есть. Сюда же, кстати, еще ведь не добита тема транзишена.

**Comment by soitanen** [comment]
Я точно помню, что если у тебя введен заход, а ты затем нажимаешь кнопку
dep/arr - то внизу справа будет ERASE ARR (так сделано точно в мадженте).
Возможно что слева есть возможность стереть SID.
А пилот на это сказал, что ему не хватает возможность сделать DELETE во
многих полях

ср, 10 окт. 2018 г. в 0:31, ponemetski <notifications@github.com>:

**Comment by soitanen** [comment]
тут вроде все ок
