### ISSUE TITLE
Работа LNAV

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#103]
На длинных расстояниях между точками (100-200 миль и более) ведет не от точки к точке, а просто к точке, уводит куда-то в сторону от линии маршрута нарисованной. Что-то с алгоритмом расчета бокового уклонения.

**Comment by ponemetski** [comment]
не до конца понятно, есть есть возможность скрин или фото ND то будет лучше

**Comment by ponemetski** [comment]
не до конца понятно, есть есть возможность скрин или фото ND то будет лучше

**Comment by soitanen** [comment]
Я картинку нарисую что было, но чуть позже.

сб, 29 сент. 2018 г., 0:38 ponemetski <notifications@github.com>:

**Comment by soitanen** [comment]
маршрут для воспроизведения
UUWW - ULLI
полосу берем 01 (в плейне может быть  02)
схема выхода OKL01D
схема прилета в пулково - по идее любая, в моем примере через точку GENPA

**Comment by ponemetski** [comment]
у меня используется формула 
http://www.movable-type.co.uk/scripts/latlong.html#cross-track
как будто по ней должно верно считаться, хотя я не уверен

**Comment by ponemetski** [comment]
возможно нужно считать еще along-track distance

https://math.stackexchange.com/questions/161335/coordinates-of-interception-point-y-with-xy-being-the-shortest-distance-of-x-to

**Comment by ponemetski** [comment]
нашел еще библиотеку для расчетов
https://www.navlab.net/nvector/#example_10

**Comment by ponemetski** [comment]
OKLIT 55.833333  37.349722
GENPA 59.106111  31.811944

**Comment by ponemetski** [comment]
теперь курс обновляется в процессе полета, 
можно проверять

**Comment by ponemetski** [comment]
в итоге самое дальнее за полет отклонение от нарисованной линии на ND
<img width="1280" alt="screen shot 2018-10-08 at 00 20 27" src="https://user-images.githubusercontent.com/1931079/46587186-fb004380-ca90-11e8-9157-8e7afbbd0466.png">
при этом в консоли видно что отклонение которое мы рассчитываем по координатам ничтожное  

возможно линия на ND не совсем точно рисуется

**Comment by soitanen** [comment]
Вроде все в итоге хорошо, но вот в зависимости от скорости не очень точно держит линию. У нас задается один коэффициент без зависимости от скорости, может есть смысл его завязать на TAS. Кроме того, у нас угол подхода ограничен 30 градусами (когда он в стороне от трассы и летит к ней). Может есть смысл увеличить его до 90, или хотя бы до 60? а то вроде он хочет подлететь к линии схемы, но не успевает из-за малого угла (это все в схема улета-прилета на маленьких скоростях вчера экспериментировал). Или вообще сделать более точный расчет, мы же умеем считать ЛУР, тут разница в курсах есть, скорость есть, можно прямо четко высчитывать точку начала доворота на линию.

**Comment by ponemetski** [comment]
> lnav: крен на разворот считается как разница курсов умноженная на 0.5, но не более 23 градусов

**Comment by ponemetski** [comment]
можно проверять

**Comment by ponemetski** [comment]
созданы две другие issue 
#127 
#156
