### ISSUE TITLE
Transition altitude

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#104]
На странице Performance справа внизу есть поле ввода Transition altitude.
1. Оно должно автоматически заполняться данными из выбранной схемы выхода на странице Departure.
2. Когда подходим к высоте перехода, то значение давления на ПФД должно становитсья желтым в раме, чтобы мы не забыли переставить давление.

И по давлению: когда переходим на стандарт , то белое предустановденное давление поменяется только когда мы мы его поменяем. Т.е. летим с давлением 1017, нажимаем СТД. Появляется зеленая надпись СТД, а белой надписи 1017 быть не должно. у нас появляется.

**Comment by ponemetski** [comment]
> Когда подходим к высоте перехода, то 

какие возьмем критерии подхода?

**Comment by ponemetski** [comment]
готово, можно проверять
по умолчанию в цду переход 18000, можно поменять указав новое значение

**Comment by soitanen** [comment]
Откуда будет браться уже в полёте обратная цифра при переходе вниз, т.е. ИТ эшелон перехода? Сейчас как я понял, он равен высоте перехода

**Comment by ponemetski** [comment]
да, берется оттуда же, идея была в том что сверху эшелона давление другое и
поэтому индикэйтед альтитьюд, скоторым мы всегда сравниваем, другой

пт, 11 янв. 2019 г. в 13:42, Michael Soitanen <notifications@github.com>:

**Comment by soitanen** [comment]
Transition level ставится на страничке DES FORECAST, FCOM page 1527

Transition Level (TRANS LVL)
Normally displays FL180 as the assumed descent transition level.
Changes automatically if an arrival procedure having a different stored value is
entered.
Manual entry allowed and takes priority.

**Comment by ponemetski** [comment]
для задания transition level создал #164 
остальное работает
