### ISSUE TITLE
Takeoff config

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#105]
Нет лампочки и сигнализации takeoff config при взлете в не взлетной конфигурации

**Comment by ponemetski** [comment]
нашел досадный баг, 
одним из условий горения ламп было указано что руд должны быть больше 80 а у нас там значение от 0 до 1
теперь загорится если хотябы один из рудов выдвинут на 10% своего хода

**Comment by soitanen** [comment]
10 мало, на рулении больше двигают. Поищу у себя точную цифру

ср, 3 окт. 2018 г., 0:04 ponemetski <notifications@github.com>:

**Comment by ponemetski** [comment]
Было 80% но я так понял это много

**Comment by soitanen** [comment]
- TAKE OFF conf warning sounds when either or both THRUST LEVERS pass 30° for classics and 53° for NGs

а угол у нас 0-65 градусов. 53/65 = 81% даже. так что надо вернуть. Как я понял, было 80 вместо 0.8

**Comment by ponemetski** [comment]
готово, можно проверять

**Comment by soitanen** [comment]
проверил на софте, на железе вроде никто не жаловался
