### ISSUE TITLE
Кнопка N1 и реакция

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#109]
По процедуре когда мы взлетели у нас автомат тяги через какоето время переходи в режим ARM, а тяга остается взлетная. Когда режим АРМ, то нажатием кнопки Н1 мы должны перейти в уменьшенную для набора высоты тягу. Сейчас быстро морагет Н1, тратл хол и обратно АРМ. Надо подумать как это реализовать.

**Comment by ponemetski** [comment]
1) а значение уменьшенной для набора тяги у нас это по таблице maxN1Clibm? (у нас есть еще таблицы takeOffN126k и maxGoAround)

2) сейчас два куска кода которые про это вот такие
```c#
if (_afds.AtState == AtState.N1 && _afds.PitchState == PitchState.TO)
{
    if (DataVIndKias >= 84)
    {
        _afds.AtState = AtState.ThrHld;
    }
}
```
```c#
// takeoff ThrHld mode
if (_afds.AtState == AtState.ThrHld)
{
    if (PfdIndAlt - takeOffArptAlt > 800 && DataLastFlightTimeSec > 10)
    {
        _afds.AtState = AtState.Armed;
        // (1)
    }
}
```
похоже вот тут (1) не сбрасывается _afds.PitchState и поэтому все идет по кругу, надо ли его сбрасывать и в какое состояние?

**Comment by soitanen** [comment]
1. Да, maxN1Climb, кстати, скоро таблиц будет больше для правильного
расчета дерейта на взлете :)))
2. Питч.стейт остается тот же. Может там добавить условие "на земле",
потому что на 84-х узлах мы не летаем, после взлета перейдет в АРМ - а при
нажатии Н1 уже не пойдет по кругу. Правда получается нужно что-то типа
скриптаЖ если режим по питчу = ТОГА, автомат тяги = АРМ, нажата кнопка Н1 -
то меняется лимит по оборотам. Остальное все также остается по кнопке Н1.

пн, 1 окт. 2018 г. в 1:09, ponemetski <notifications@github.com>:

**Comment by ponemetski** [comment]
добавил две проверки, должно работать, но я не уверен в полном отсутствии глюков, нужно протестировать

**Comment by soitanen** [comment]
потыкал на железе - вроде хорошо все
