### ISSUE TITLE
Список доработок по системам

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#11]
- не горит при тесте лампа кнопка cargo fire discharge #82
- прописать логику работы ответчика, он же transponder. Все 4 цифры от 0 до 7. Должны отправляться в X-Plane. #79 
- отсутствует сдвиг нейтрали штурвала при использовании Aileron trim #80
- [x] сделать кривую отклика тормозов. Не забываем, что отключение автомата торможения, постановка на стояночный и снятие с него берется не по положению педали, а по давлению в тормозах, т.е. по сигналу в симулятор.

Сигнал с педали   |   Сигнал в симулятор
--- | ---
0|0
0.44|0.2
0.7|0.97
1|1

- [x] сделать фильтр сигнала с РУДов
- [x] обеспечить правильную логику выхода спойлеров на земле - работа упора на Flight Detent
- [x] активировать автоматический выход спойлеров на земле и заход их обратно при даче газе
- [x] проверить логику работы малого газа у земли и в воздухе - в тестовых полетах иногда малый газ наземный начинал в воздухе работать
- [x] активировать автомат тормозов
- [x] в режиме реверса обороты двигателя не должны быть выше 82%
- Допилить и использовать магнитное склонение из World Magnetic Model, а не из X-Plane #46
- [x] Сделать чтобы когда автопилот управляет триммером, колесо триммера крутилось

**Comment by ponemetski** [comment]
по лампе просьба проверить в веб морде и на железе, скорее всего просто не видно света из-за конструкции лампы

**Comment by soitanen** [comment]
ну да, на морде загорается.
