### ISSUE TITLE
CDU perf isa dev

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#110]
Как реализована логика расчета ISA DEV на странице perf? А то там пипец какой-то выводится

**Comment by ponemetski** [comment]
для `isa dev` просто вводится значение и оно оно запоминается
есть завязка с `t/c oat`,  оно равно `isa dev` минус 29 градусов цельсия

нужна информация как работать с этим значением

**Comment by soitanen** [comment]
ISA - international standard atmospehere. Есть табличка в википедии где каждой высоте соответствует своя температура. deviation - мы задаем, соответственно, насколько у нас отличается температура от стандартной уже на эшелоне. соответственно вводим ISA DEV - автоматом считается T/C OAT. И работает обратная тема - ввели температуру на эшелоне - посчитается ISA DEV. В реальном самолете все это учитывается в каких-то расчетах, нам достаточно просто косметики. Т.е. берем табличку температура-высота, от нее отклоняемся, чтобы не вылезало космических значений как сейчас.

**Comment by soitanen** [comment]
Косяк. Ставлю для проверки ISA DEV = 0. Меняю эшелон. 360 эшелон - на эшелоне -56. на 361 эшелоне и выше +56!!! Где-то что-то перепутано.

**Comment by ponemetski** [comment]
нашел касяк, у меня при высоте выше 11км (как раз 360 эшелон) всгда возвращается 56, а должно -56 (судя по википедии выше 11км температура почти не меняется)

**Comment by soitanen** [comment]
теперь ОК
