### ISSUE TITLE
логика теста ламп AP-AT-FMC

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#113]
Тумблер тест почему-то не дает заггорания красных ламп, хотя они красным моргать умеют. Плюс есть вопрос - каждый тумблер тестирует индивидуальный блок ламп или еще и лампы соседа.

**Comment by soitanen** [comment]
Попросили пилотов проверить, пока подтверждают, что тумблер тест зажигает лампы только на своем пульте без соседнего.

**Comment by ponemetski** [comment]
поправил, можно проверять

**Comment by soitanen** [comment]
на софте проверил, думаю, что на железе проблем быть не должно. закрываю.
