### ISSUE TITLE
Паразитный звук двигателя

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#115]
при долгой работе (2-3 часа) enginesound.exe появляются какие-то дополнительные паразитные звуки. вопрос решается выключением программы и ее перезапуском, паразитный звук исчезает. Иногда какой-то звук не начинает проигрываться.

- [x] пере инициализировать все звуки при перестановке самолета
- [x] пробовать инициализировать звук несколько раз потому что иногда некоторые выпадают

**Comment by ponemetski** [comment]
изучал код, ничего такого из-за которого через 2-3 часа может сломаться пока не нашел.
нужно описание того что происходит когда начинаются эти паразитные звуки:
1) они постепенно появляются или резко?
2) что в это время с потреблением процессора и памяти?
3) есть ли тормоза в изменении звука от оборотов? звук стал не медленнее подстраиваться под обороты?
4) насколько зависит время появления паразитных звуков от частоты изменения питча? то есть если руды неподвижны то паразитные появятся позже чем если постоянно активно менять обороты?
5) может удастся записать в вотсап паразитный звук?
вопросы конечно каверзные, но если есть хотя бы по части из них ответы то будет более понятно что делать

**Comment by ponemetski** [comment]
добавил в конфиг параметр pitchOsamp
значение по умолчанию 4 (то есть до того как добавил тоже)
это поличество сэмплов для пича
единственное что нашел это то что если поставить 32 то будет хорошее качество (не ясно что будет с процессором при этом)
думаю можно поиграть попрововав значения 8 16 32 64

**Comment by ponemetski** [comment]
при перестановке самолета теперь все звуки переинициализируются, что должно решить проблемы с паразитными звуками

**Comment by soitanen** [comment]
Надо обновить только engine sound, или и фмс? Внесены ли изменения в
фмс-прокси?

чт, 27 сент. 2018 г., 18:00 ponemetski <notifications@github.com>:

**Comment by ponemetski** [comment]
только что обновил архив v14 еще раз, если успел скачать перекачай плиз
обновить нужно только EngineSounds

**Comment by soitanen** [comment]
Похоже нормально все, не слышу паразитного теперь.
