### ISSUE TITLE
ThrHld

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#12]
включается на:
- 84 узлах а N1 & Toga

выключается при: 
- радио высоте > 400 футов & времени в полете > 18 сек

**Comment by soitanen** [comment]
Не срабатывает перехеод обратно в ARM. Алгоритм проверки:
1. Стоим на полосе.
2. Армируем автомат тяги, ставим скорость 144, закрылки 5, триммер примерно 4.7-5.0
3. Жмем ТОГА.
4. Разбег, отрыв. Засекаю свои секнудомером время. Через 18 секунд я выше 400 футов, но режим все также в THR HLD. Перешел в ARM почему-то через 56 секунд...

**Comment by soitanen** [comment]
С новой переменной работает правильно.
