### ISSUE TITLE
Выход из режима approach

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#122]
Заармировали approach, захватили и курсовой и глиссадный маяки. Погасла кнопка app. Нажимаем кнопку VS - сейчас он из режима глиссада выпадает в вертикальную скорость, а должен игнорировать это нажатие. Такая же реакция (игнор) должна быть и на кнопку level change, alt hold, vnav, lnav, hdg sel, vorloc, когда у нас активен заход по глиссаде (не проверял все кнопки).

**Comment by ponemetski** [comment]
можно проверять

**Comment by soitanen** [comment]
ок
