### ISSUE TITLE
Звук реверса

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#123]
Звук реверса играется один раз и резко обрывается, хотя реверс еще включен. Также слишком резко вырубаются основные звуки двигателей при включении реверса, надо продумать как сделать лучше.

**Comment by ponemetski** [comment]
В конфиге указать можно несколько звуков которые начнут единоразово играть при открывании створок реверса:

```ini
# started when "reverser gate is 3"

Reverser.mode = reverser
Reverser.src = n2
Reverser.pitch = 0 1.0; 102 1.0
Reverser.volume = 0 1.0; 102 1.0

SecondReverser.mode = reverser
SecondReverser.src = n1
SecondReverser.pitch = 0 1.0; 102 1.0
SecondReverser.volume = 0 1.0; 102 1.0

...
```

Также можно указать несколько звуков которые будут играть все время пока открыты створки реверса:

```ini
# reverser sounds

Idle@reverser.src = n2
Idle@reverser.pitch = 19 1.0; 34 1.7
Idle@reverser.volume = 10 0.05; 19 0.40; 27 0.82; 34 0.05

Power@reverser.src = n1
Power@reverser.pitch = 19 1.0; 34 1.7
Power@reverser.volume = 10 0.05; 19 0.40; 27 0.82; 34 0.05

...
```

**Comment by soitanen** [comment]
Предлагаю сделать для реверса crossfade между звуками прямой тяги и обратной. На открытие и закрытие реверса по 3 секунды. Но не линейно.
время - уровень реверса (обратный уровень прямой тяги)
0 - 0
2 - 0.3
3 - 1
Или сделать возможной настройку этого перехода.

**Comment by soitanen** [comment]
Сейчас я сделал , что большинство звуков прямой тяги просто продолжают играть и при обратной, получается, что нужно не crossfade делать, а только плавное нарастание громкости реверса и плавное гашение, желательно через табличку, чтобы регулировать в конфиге, а не через код.

**Comment by ponemetski** [comment]
> плавное нарастание громкости реверса и плавное гашение

1) как называются файлы реверса? их два на закрытие и открытие?
2) по каким событиям их включать выключать?
3) играть их ровно 3 секунды? резко прерывая?

**Comment by ponemetski** [comment]
добавил в конфиг вот такое:
```ini
# time for crossfade between direct and reverse in milliseconds
dirToRevTime = 3000
# interpolation table for crossfade: 
# first value - crossfade position from 0 to 1, second value - volume
dirToRevTbl = 0 0; 0.2 0.1; 0.8 0.9; 1 1
```
то есть, можно регулировать длительность кросфэйда и задавать кривую зависимости громкости от времени кросфэйда

пока билд не выкладывал, завтра выложу после предварительного тестирования

**Comment by soitanen** [comment]
работает
