### ISSUE TITLE
Управление паузой через тумблер PASS OXY

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#124]
Необходимо реализовать возможность быстрой постановки на паузу через тумблер PASS OXY. Если активен тумблер - то на паузе. Не активен - летает.

**Comment by ponemetski** [comment]
`sim/operation/pause_toggle`

**Comment by ponemetski** [comment]
готово

**Comment by soitanen** [comment]
работает на софте, если на железе будет глючить (что вряд ли) - переоткрою.
