### ISSUE TITLE
Полет без подвижности

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#126]
Сделать для тренажера только на инструкторском пфд моргающую надпись platform not up в случае если самолёт в воздухе, а подвижность выключена. Надпись должна моргать минуту, а затем выключаться, чтобы не мешать каким-то тестовым полётам действительно без подвижности.

**Comment by ponemetski** [comment]
- в файле статуса платформы дата и время в формате yyyyMMddHHmmss
- программа платформы обновляет его несколько раз в минуту (ульяновская версия каждые 2 секунды) 
- мне кажется что момент отрыва от земли уже слишком поздно для того чтобы сигнализировать о том что платформа внизу (там же как раз самое ускорение на разбеге) 
- может показывать сигнализацию только когда граунд спид больше 5 и мы на земле? заодно в тестовом полете мешать не будет (потому что погаснет как только мы оторвались от земли)

**Comment by soitanen** [comment]
Наверное можно и как ты предложил. Главное, чтобы инструктор смотрел на приборы на разбеге :) На самом деле редкая штука, но может срабатывать на этапе начала эксплуатации, именно тогда и совершаются "детские ошибки".

**Comment by ponemetski** [comment]
готово

нужно добавить в config.txt фмс строку с указанием файла состояния платформы (файл то же самый которые указан в конфиге MbMonSvc
```ini
platform.status.file = C:\Extrino\...txt
```

если грайнд спид больше 5 и мы на земле то у инструктора будет надпись:

<img width="499" alt="screen shot 2018-11-23 at 23 33 25" src="https://user-images.githubusercontent.com/1931079/48959745-7900a700-ef78-11e8-8438-904a5a930e42.png">

**Comment by soitanen** [comment]
работает
