### ISSUE TITLE
Захват локалайзера в тивате

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#128]
Локалайзер рисуется на пфд, но в режиме вор лок не захватывается. Аэропорт lytv, частота 111.3

**Comment by ponemetski** [comment]
@soitanen как будет возможность, можешь плиз проверить и если нужно я добавлю 13 навигационный тип как локалайзер

**Comment by ponemetski** [comment]
добавили 5 тип навигации и заработало
