### ISSUE TITLE
Pitch: Toga, GA; Roll: GaTrack, WingLevel

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#13]
Нужно описание работы. Я так понимаю что все эти режимы связаны с процессами take off / go around

Режимы roll
- [x] GaTrack
- [x] WingLevel

Режимы pitch
- [x] Toga
- [x] GA

**Comment by soitanen** [comment]
По сути режим по тангажу (Pitch) TOGA & GA такой же, как и режим LVL CHG, он же MCP SPEED по тангажу. Т.е. даем желаемую скорость, получаем на выходе тангаж для поддержания этой скорости. Приколы здесь больше в самой подаваемой скорости.

Итак. Режим TOGA.
Стоим на земле, директора включены, но на экране их пока быть не должно.
Нажимаем кнопку TOGA.
То что было в окошке скорости на МСР надо записать в какую-то отдельную переменную. Это будет MCP_V2.
Target pitch = -10 градусов до скорости 60 узлов по прибору.
На 60 узлах target pitch прыгает на 15 градусов, причем в этом переходе нет фильтрации движения стрелки, тангаж именно перескакивает.
Отрываемся.
Если оба двигателя исправны, то наша желаемая скорость, которую помогают выдерживать директорные стрелки = MCP_V2 + 20. Если отказ двигателя, то:
наша скорость меньше MCP_V2 -> target speed = MCP_V2
MCP_V2 < наша скорость < MCP_V2 + 20 -> target speed = current_speed
MCP_V2 + 20 < наша скорость -> target speed = MCP_V2 + 20
Во время всех этих изменений скорость на MCP не меняется, на PFD тоже не меняется, просто директора помогают держать другую скорость, чем мы выставили.

Следующий прикол: при выходе из режима TOGA в любой другой режим в окошко скорости на МСР записывается MCP_V2+20. Т.е. взлетаем с V2 144. Директора помогают выдерживать 164. Нажимаем кнопку LVL CHG, или VS, или автоматически срабатывает ALT ACQ - в МСР 144 меняется на 164.

Еще прикол: если мы идем в TOGA и стали увеличивать скорость на МСР - то пока она меньше, чем MCP_V2+20, то директора помогают держать MCP_V2+20, а когда станет больше - то уже выставленную на MCP скорость. И в таком случае при выходе из TOGA эта скорость так в MCP и останется, на V2+20 не перейдет.

Еще момент: TOGA не может работать в автопилоте в принципе. Если включена TOGA и мы нажимае кнопку включения автопилота, то режим по тангажу автоматически перейдет в MCP SPD, а автомат тяги в N1 (аналог нажатия LVL CHG).

Это все было про тангаж.
По крену проще. Нажатие TOGA активирует режим WING LEVEL. Он никак не анонсируется. Его суть - target bank = 0. Т.е. при возникновении крена директорная стрелка помогает его убрать. при отключении режима TOGA, если не был выбран до этого какой-то другой режим по тангажу, то директорная стрелка по крену исчезает. Если был включен автопилот - то крен будет в режиме CWS ROLL.

**Comment by soitanen** [comment]
Теперь про Go Around

В момент нажатия кнопки берется текущий track, он же становится заданным и активуется режим track hold (которые опять же не анонсируется). В нем директора помогают держать уже не heading, а track.
Второй вариант - мы в FMS выбрали какой-то заход, в котором заложена схема ухода на второй круг. Тогда при нажатии кнопки ухода автоматически активируется LNAV и будет уводить на второй круг по схеме.

По скоростям. При нажатии кнопки гаснет окошко скорости, но на PFD заданная скорость все равно будет. Ее значение рассчитывается автоматически в зависимости от положения закрылков. Скорость плавно интерполируем при уборке.

Положение закрылков | Target speed
-------- | -------
0 | 220
1 | 200
2 | 190
5 | 180
10 | 180
15 | 170
25 | 160
30 | 150
40 | 150

Тангаж - как в pitch mcp speed, есть особенность работы директора - он не отойдет вверх или вниз больше чем на 4 градуса от текущего тангажа, чтобы пилот типа плавнее работал штурвалом.

**Comment by soitanen** [comment]
Забыл написать про тангаж при TOGA. Вот на 60-ти узлах он переключился на 15 градусов. Дальше он зависит от вертикальной скорости. До 300 фт/мин он 15. От 1200 и выше он целиком равен тому, что посчитала нам система для выдерживания скорости. А между 300 и 1200 он плавно переходит из одного в другое: pitch = 15 * k + (1-k) * calculated_pitch  k=1 при 300 и =0 при 1200.

**Comment by ponemetski** [comment]
ограничения по макс крену
До 400 футов по радиовысотомеру - 8 градусов в любом режиме кроме LOC, выше - да, до 30

**Comment by ponemetski** [comment]
по ГА - выше 2000 футов по радиовысотмеру ничего происходить не должно

**Comment by ponemetski** [comment]
- [ ] Камиль Михаил, [Nov 25, 2017, 9:50:03 PM]:

- [ ] в ГА у тебя не зачитстилось окно скорости, а на PFD оставалась индикация из МСР, хотя тут как раз, по сравнению с ТОГА, будет реальная заданная сорость

- [ ] режим по тангажу должен быть на FMA как TO/GA, а не G/A
переход в ALT HOLD не вызвал переход в MCP SPD по автомату тяги, а должен

**Comment by ponemetski** [comment]
в итоге ролл рейт работает вот так, нужно проверить
    
    vorOnCourse = (Abs(navLoc) < 0.5 точки) && Abs(_180(course - magTrack)) < 5 градуса

            if (_afds.RollState == RollState.Loc && vorOnCourse)
                targetRollRate = Range(targetRollRate, -5.5, 5.5);
            else if (_afds.RollState == RollState.Loc)
                targetRollRate = Range(targetRollRate, -7, 7);
            else if (_afds.RollState == RollState.Vor && vorOnCourse)
                targetRollRate = Range(targetRollRate, -1.3, 1.3);
            else 
                targetRollRate = Range(targetRollRate, -4, 4);

**Comment by ponemetski** [comment]
- [ ] Еще момент: TOGA не может работать в автопилоте в принципе. Если включена TOGA и мы нажимае кнопку включения автопилота, то режим по тангажу автоматически перейдет в MCP SPD, а автомат тяги в N1 (аналог нажатия LVL CHG).

1) разумеется автопилот при этом включится?
2) на время тестов надо оставить сделал эту фичу при нажатии автопилота В

**Comment by soitanen** [comment]
ошибки на момент проверки:
- [ ] после перестановки самолета на полосу в плейне в веб-морде стоят обе галочки FD (включены директора физическим тумблером, как я понимаю), но ни одна лампочка МАСТЕР не горит. Индикация FD тоже не горит (а должна). При этом если я нажимаю кнопку ТОГА, то активируется режим N1 в автомате тяги, а в тангаже пусто. Это неверно. Активация автомата тяги происходит как бы по событию в режиме тангажа. Т.е. нажали кнопку, активировался режим ТОГА в тангаже, автомат тяги это увидел и тоже активировался. Причем если ты нажимаешь ТОГА без автомата тяги, то директора будут помогать взлетать. Но если ты в процессе взлета включишь тумблер автомата тяги - то он будет просто заармирован, не будет помогать никак до момента наступления какого-либо события, активирующего автомат.

**Comment by soitanen** [comment]
предлагаю это пока закрыть. будут вылезать баги - буду создавать отдельные issue.
