### ISSUE TITLE
Скрипт обновления НавДаты

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#130]
Сделать скрипт для обновления навдаты. У меня линукс, под винду не смогу сделать сам.
На Я.Диске в Extrino/NavData-Aircraft-Lua/ лежит архив navdata_native.zip Когда будет выходить новая версия, то я буду подменять этот архив, сохраняя имя. Тогда запустив скрипт он должен распаковать сожержимое в C:/Extrino/NavData (или куда там?).

В идеале вообще сделать через CDU, чтобы пилот мог просто нажать кнопки, так как я.диск синхронизируется автоматически.
Menu -> там какое-то меню CONFIG -> UPDATE NAVDATA - загружает файл, распаковывает, и перезапускает FMS, чтобы подгрузить.

И все это, наверное, штатными средствами винды, чтобы не быть зависимыми от 7zip и прочих винраров.

**Comment by ponemetski** [comment]
@soitanen, как я понял это готово?

**Comment by soitanen** [comment]
ну да. на моей стороне сделано. По идее там еще один файлик придется добавлять в папку с навдатой (тоже автоматизирую), чтобы парсить его и брать высоты/эшелоны перехода
