### ISSUE TITLE
QuickFix: Максимальный поворот штурвала

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#131]
У нас максимальный поворот штурвала при убранных и выпущенных закрылках захардкоден. Цифры взяты от 737 Классики, так как от NG я не находил. Есть подозрение, что у NG лимиты все-таки побольше, плюс тут для некоторых аэродинамических тестов потребовалось чтобы штурвал мог повернуться гораздо больше. Прошу вынести две этих цифры в конфиг.

**Comment by ponemetski** [comment]
насколько я понял нам нужно вот это значение if (flapsUp) 0.195 else 0.287
находится оно в ApRoll то есть в том функции которая делает из угла по крену значение на которое нужно подвинуть штурвал

**Comment by ponemetski** [comment]
в конфиг нужно добавить 
```ini
# ap roll cmd range
system.config.ApRollCmdFlapsUp = 0.195
system.config.ApRollCmdFlapsDn = 0.287
```

можно проверять

**Comment by soitanen** [comment]
работает
