### ISSUE TITLE
Стабилизатор внезапно уходит в ноль

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#133]
В Краснодаре опять стал появляться глюк (я его сам ловил еще тогда весной на открытии), что стабилизатор резко до упора уходит мгновенно на самое переднее положение (0 или -0.2, по веб-морде не успевают проверять). Можешь как-то проверить куски кода где мы посылаем стабилизатор в симулятор и расчитываем его до этого?

**Comment by ponemetski** [comment]
1) вообще не могу понять почему так происходит
3) происходит это при нажатии на штурвале триммера вниз? от высоты зависит? директоры включены а автопилот выключен?
1) **добавил грубое ограничение, если новое значение триммера отличается от старого на 1 юнит, то не посылать новое значение в симулятор**
4) если будет себя странно вести стабилизатор (с учетом предыдущего пункта) например скакать на единицу или наоборот не двигаться когд должен то нужно постараться максимально точно запомнить и попробовать воспроизвести

**Comment by ponemetski** [comment]
починил проблему с кручением колеса триммера в автопилоте

**Comment by ponemetski** [comment]
на самом деле
починил проблему с кручением колеса триммера в автопилоте

**Comment by soitanen** [comment]
теперь работает
