### ISSUE TITLE
Делать громкость всех звуков нулевой если симулятор на паузе

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#134]

**Comment by ponemetski** [comment]
готово, завтра сделаю билд

там же исправлена ошибка по которой ты присылал лог вчера, можно будет скинуть логи после пары дней работы, чтобы я их проверил на всякий случай

если будет время и возможность, нужно глянуть в консоли переменную DataPaused.
это нужно сделать именно на тренажере в рио, где используется FmsProxy.
переменная должна меняться на 1 при постановке на паузу

**Comment by soitanen** [comment]
жду билд, но проверю на объекте только в воскресенье (соответственно к воскресенью утро хотелось бы билд).

**Comment by soitanen** [comment]
да, для паузы какую-то новую галку надо ставить?

**Comment by ponemetski** [comment]
не надо

пт, 5 окт. 2018 г. в 18:44, Michael Soitanen <notifications@github.com>:

**Comment by ponemetski** [comment]
залил архив "_v18_pause"

глянул конфиг, звуки которые не используются можно просо закомментить (или удалить), это даст небольшой но прирост производительности

**Comment by soitanen** [comment]
Переменная меняется, звуки глушатся. Логи пришлю после работы. Лишние звуки у меня уже закомменчены, просто еще не выкладывал.
