### ISSUE TITLE
Оптимизировать количество CPU необходимое звукам двигателей

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#135]

**Comment by soitanen** [comment]
Баг на самом деле оказывается критический. В новосибирске процессор стоит слабее, чем в вегасе, и левый компьютер, на котором и крутятся двигатели, за день несколько раз мертво зависает, спасает только перезагрузка кнопкой на корпусе. так что надо как-то думать в этом направлении (уменьшать нагрузку. причем значительно), либо процессор другой здесь вообще ставить.

**Comment by ponemetski** [comment]
https://markheath.net/post/varispeed-naudio-soundtouch
https://www.surina.net/soundtouch/README.html
https://github.com/naudio/varispeed-sample

**Comment by ponemetski** [comment]
удалось оптимизировать потребление cpu примерно в три раза

**Comment by soitanen** [comment]
не закрываю, так как известно, что программа у нас падает. ПРичем падает на всех 4-х точках, где она установлена.
