### ISSUE TITLE
Моргание рамки скорости

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#136]
Indicates current calibrated airspeed in knots.
When current airspeed decreases into the minimum maneuver speed amber bar:
• airspeed readout box turns amber and flashes for 10 seconds
• voice alert annunciate “Airspeed Low, Airspeed Low” once
• box returns to white when airspeed is above minimum maneuver speed.

Это из ФКОМ.
Надо сделать так, что если скорость попала в НИЖНЮЮ желтую или НИЖНЮЮ красную зону (по сути все, что ниже желтой зоны), то моргает 10 секунд (как высота), потом просто желтая рамка, вроде по тому видео что я видел - тоже жирная. Голосовое делать не будем. Ну и обратно в белый цвет по условию из ФКОМа - т.е. выход из этой желтой зоны.

**Comment by ponemetski** [comment]
можно обновить фмс+гц и протестировать

**Comment by soitanen** [comment]
работает
