### ISSUE TITLE
автотриммирование в автопилоте

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#140]
Поставил новый (относительно) билд в краснодар - тоже как и в вегасе начались приколы по автотриммированию. Насколько я помню по коду, у нас автопилот двигает виртуальный руль высоты, а вот автотриммирование случается только в том случае, если реальное положение колонки уходит за определенный предел. Я предлагаю поменять это, чтобы триггером для триммирования было виртуальное положение руля, тогда глюки с раскалибровкой то ли штурвала, то ли мотора уйдут.

**Comment by ponemetski** [comment]
теперь используется YokesElevatorHwTargetPos, это та переменная которая является виртуальным положением штурвала

**Comment by soitanen** [comment]
вроде все ок
