### ISSUE TITLE
PFD Pitch Limit Indication

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#144]
<img width="859" alt="screen shot 2018-10-25 at 01 47 49" src="https://user-images.githubusercontent.com/1931079/47466068-340e1700-d7f8-11e8-9e9b-bacc486d39d9.png">

вопросы
- эти желтые штучки всегда в одном положении? или двигаются вниз вверх от каких то параметров типа скорости и тп
- насколько скорость должна быть медленной чтобы они показались при убранных закрылках? и которая из скоростей? IAS?

**Comment by soitanen** [comment]
Они, по сути, привязаны к углу атаки. У нас же стик шейкер из симулятора срабатывает вроде на 14 градусах угла атаки, вот и получаем, что они выше символа самолёта на запас по углу атаки. По второй части вопроса - я думаю, что они появляются не совсем от скорости, а тоже от угла атаки, например, если этот запрос становится 2-4 градуса - тогда появляются. Точной информации не находил.

**Comment by ponemetski** [comment]
угол атаки это DataAlphaDeg (18 галка нулевое значение)? 
у нас автопилот отключается если оно больше 16 

> У нас же стик шейкер из симулятора срабатывает вроде на 14 градусах угла атаки

эта логика похоже внутри иксплейна. у нас стикшейкер срабатывает если в галке 127 шестое значение (начиная с нуля) будет 1

---

> вот и получаем, что они выше символа самолёта на запас по углу атаки. 

точно ли двигаем эти желтые штуки вверх вниз? тогда не понятно где у них нулевое положение и в каких пределах нужно двигать. ведь угол атаки у угол питча не одно и тоже как я понял. 
я смотрел видео, и там он как будто бы не двигался, хотя и самолет летел ровно 

---

берем 14 как границу?
получается если закрылки выпущены, то желтые штуки горят всегда, если закрылки убраны то только если угол атаки больше чем 10-12 градусов? (может возьмем 11 для нашего случая)

**Comment by soitanen** [comment]
угол тангажа нас не особо волнует в данном случае. мы рисуем эти желтые рога оленя выше чем символ самолета на = (14 - УА) * град2пиксель. В итоге может получиться так, что они вроде и на одном месте, хотя угол атаки меняется, но это логично, ведь тангаж тоже меняется (это в случае горизонтального полоета с разной скоростью).

**Comment by soitanen** [comment]
сейчас пересмотрел видосы, мне кажется, что в них зашито не 14, а 16 градусов. Поищу, где в настрйоках самолета стикшейкер настраивается, может мы можем перенастроить

**Comment by soitanen** [comment]
на боинге 767 вот такое нашел, возможно тут схожая логика:
"The additional Pitch Limit Indicator will be displayed when:
(a) The flaps are up, and
(b) The IAS is less than 1.14 ´ stick shaker speed or within the lower
amber band, and
(c) The Mach number is less than 0.70."

**Comment by soitanen** [comment]
и вот судя по увиденной мной информации, когда flaps UP - то лимит 14 градусов, а когда закрылки выпущены, то лимит 16 градусов. И красная метка на индикаторе угла атаки тоже сдвигается, соовтетственно.

**Comment by ponemetski** [comment]
>на боинге 767 вот такое нашел, возможно тут схожая логика:
"The additional Pitch Limit Indicator will be displayed when:
(a) The flaps are up, and
(b) The IAS is less than 1.14 ´ stick shaker speed or within the lower
amber band, and
(c) The Mach number is less than 0.70."

то есть мы берем эти условия как условия для появления рогов и уже рисуем на определенной высоте, которая зависит от угла атаки

на скорости меньше 105 узлов рога оленя встают на тангаж 13.5 градусов (примерно, конечно) и перестают колыхаться

**Comment by ponemetski** [comment]
готово, можно проверять

**Comment by soitanen** [comment]
ok
