### ISSUE TITLE
Рисовать маршрут цветом CYAN

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#147]
Когда мы начали вбивать маршрут в CDU - то на карте он должен появляться в виде штрихов цвета CYAN, когда нажали activate - он стал белым, но все еще штриховым, когда нажали EXEС - сплошной magenta. У нас сейчас вот этот момент в CYAN не работает.

**Comment by ponemetski** [comment]
готово

**Comment by ponemetski** [comment]
поправил
