### ISSUE TITLE
индикатор заданной вертикальной скорости

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#149]
Должен быть не одинарной розовой линией, а двойной. Также на видео увидел, что по слоя этот розовый маркер рисуется выше, чем стрелка вариометра.
![image](https://user-images.githubusercontent.com/2819664/47855163-d6c82600-ddf4-11e8-9ba6-7fa5db2ed03e.png)

**Comment by ponemetski** [comment]
готово, можно проверять

**Comment by soitanen** [comment]
ok
