### ISSUE TITLE
VOR режим

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#15]
Это то же самое что LOC режим но когда мы поймали VOR маяк.

**Comment by ponemetski** [comment]
Собственно вопрос 1

        // 0 = NOTHING: Your radio does not receive any type of navaid. That could mean that is is not tuned correctly or you are not "in range" 
        //     or not "in good position" or the radio system failed or you name it...
        // 2 = NON-DIRECTIONAL BEACON (NDB): Your radio is receiving a NDB signal. You will get this from your ADF1 and ADF2 radios normally.
        // 3 = VOR / VOR-DME / VORTAC: Your radio is receiving a VOR or a VOR-DME or a VORTAC signal. Which one of those? You don't get this 
        //     information from this single dataref.
        // 4 = LOCALIZER (LOC) AS PART OF AN ILS: Your radio is receiving a signal from a localizer installation which is part of an ILS system.
        // 5 = LOCALIZER (LOC): Your radio is receiving a signal from a localizer installation which is NOT part of an ILS system.
        // 6 = GLIDESLOPE (GS) AS PART OF AN ILS: Your radio is receiving a signal from a glideslope installation which is part of an ILS system.
        // 12 = DISTANCE MEASURING EQUIPMENT (DME) AS PART OF AN INSTALLATION: Your radio is receiving a DME signal from a DME station that is
        //      "part of an bigger installation" as a VORTAC, VOR-DME or ILS.
        // 13 = DISTANCE MEASURING EQUIPMENT (DME): Your radio is receiving a DME signal from a DME station that sits their on its own.

нас интересуют цифры 3 и 9 (глиссада же может ловиться вместе с VOR маяком?) 
верно?

**Comment by ponemetski** [comment]
Вопрос 2
LOC у нас используется несколько раз, везде ли нужно вставить LOC

1) при активации HDG SEL - если у нас режимы LOC и GS то HDG SEL не включится. это же относится к VOR + GS?

2) если мы в режиме LOC то мы делаем Range(targetRollRate, -5.5, 5.5);  а в VOR режиме Range(targetRollRate, -1.3, 1.3); верно?

3) pitch GS режим активируется **только** в roll LOC, верно?

4) в режиме LOC мы вычисляем targetHeading по нескольким параметрам в том числе отклонение (которое от -2.5 до +2.5 точки). потом мы этим значением кормим функцию которая уже вычисляет необходимый наклон штурвла. что делать с режимом VOR? дает ли он тоже отклонение (от -2.5 до +2.5 точки) и можем ли мы считать по тому же алгоритму?

**Comment by soitanen** [comment]
Вопрос №1 - нет, глиссадный маяк бывает только в составе курсо-глиссадной системы, т.е. ILS, таким образом захват глиссады возможен только при захвате именно курсового маяка.

Вопрос №2.
1. VOR + GS не бывает, поэтому вопрос отпадает. Если идешь в режиме VOR или LOC без GS, то нажатие на HDS SEL выбьет ведение по маяку и переведет в ведение по заданному курсу.
2. -1.3 +1.3, ЕМНИП, когда VOR + vor-on-course, мы делали расчет этой переменной.
3. Да.
4. Да, суть та же, просто ширина луча гораздо больше, поэтому будут другие коэффициенты в этом режиме.

Отличие VOR маяка от LOC в том, что LOC - это один направленный в пространстве луч, но он довольно узкий. А VOR - это 360 лучей, ты через окошко COURSE на MCP выбираешь какой тебе нужен, видишь отклонение от него и летишь куда тебе там дальше надо.

**Comment by ponemetski** [comment]
№1. "вопрос - в каком варианте может включиться режим ВОР? Да, только 3."

**Comment by ponemetski** [comment]
№2.

![photo5231457019536451720](https://user-images.githubusercontent.com/1931079/33007467-ed030c44-cddf-11e7-9e59-f3643879ed76.jpg)

4. Да, эти два на самом деле. Тут тоже можно сделать Пропорциональный и Дифференциальный. П = 12. Д = 5* П  регулируем сначала П, потом подкручиваем Д

**Comment by ponemetski** [comment]
see #18
