### ISSUE TITLE
touchdown sound

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#153]
Проверка на железе.
Сейчас в Сибирском Молле звук тачдауна слышен как при касании, так и при отрыве, т.е. ощущение что он проигрывается при переходе состояния, а не при приземлении - можешь проверить?

**Comment by soitanen** [comment]
Проводили эксперимент - держали на разбеге штурвал от себя, потом набрав явно большую скорость резко оторвались от земли - звука не было. Значит, по логике, он идет не от отрыва, а от того что на отрыве в X-Plane стойка успевает сыграть в воздух и обратно на землю, видимо. Может стоит тогда завязать звук не на касается-не касается, а на усилие на стойке, и если принять какие-то образные цифры, то проигрывать его один раз при превышении какой-то силы (образно 20%), и армировать на повторное произведение звука только если сила уменьшилась до 1% или что-то такое.

**Comment by ponemetski** [comment]
если стоять на месте на малом газу то на опоре давление 9140
если на тормозах стоять на полном газу то 3300

вот такой график на носовой опоре при взлете "козликом"

<img width="937" alt="screen shot 2018-11-12 at 20 58 50" src="https://user-images.githubusercontent.com/1931079/48366169-12e56b80-e6be-11e8-9398-047adef662c4.png">

пока сделал что тачдаун будет играть только если было давление ноль а стало больше 3000
но это не уберет звуки если мы приподняли стойку на взлете и потом уронили её (да и в принципе это наверное так должно быть потому что в жизни то мы услышим в этом случае звук)

**Comment by ponemetski** [comment]
обновил

**Comment by soitanen** [comment]
будем играть еще с самим звуком, но сама реализация ок
