### ISSUE TITLE
Мгновенный уход стабилизатора

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#155]

**Comment by ponemetski** [comment]
вегас написал - словили уход стабилизатора от себя до упора, но только дальше и них почему-то он не реагировал на дальнейшее триммирование. Вот вторая часть меян смущает, может он что-то не так распознал, а вот первая часть подтверждает мои собственные наблюдения - вдруг резко нос вниз, стрелка стабилизатора в нуле

**Comment by ponemetski** [comment]
обновил лог (на этот раз обновлять nlog.config не нужно)
добвил в лог:

```
_elevatorTrim
DataElevatorTrim, то что шлем в иксплейн
DataElevatorTrimActual,то что читаем из иксплейна (отстает на шаг от предыдущего)
ThrottleTrimWheelHwModeSw, 0 - off, 1 - on (enable motor)
ThrottleTrimWheelDirectionSw, 0 - back, 1 - forward
ThrottleTrimWheelSpeedPos, скорость вращения 0 - медленная 1 - выстрая 
ThrottleTrimIndHwTargetPos, 0.000-17.000 - in units стрелка на РУДе
ThrottleTrimEnc, показания с датчика колеса (0-65000) примерно 4 ед на оборот
YokesElevatorHwApModeSel, включен ли мотор по тангажу (так определяем A/P CMD режим)
YokesLStabTrimSel, capt переключатель триммера на штурвале 0 - center, 1 - up, 2 - down
YokesRStabTrimSel, f/o 0 - center, 1 - up, 2 - down
ThrottleStabTrimMainElecSw, тумблер stab trim main elec
_n, номер причины изменения
```

**по предыдущему логу:**
у меня в коде на каждую единицу движения колеса триммера положение триммера меняется на 0,025 и по логу я четко вижу что так и есть:
<img width="218" alt="screen shot 2018-11-21 at 00 09 56" src="https://user-images.githubusercontent.com/1931079/48803005-cd5e1980-ed21-11e8-90d9-de9a951b90f4.png">

получается как будто за 8 секунд положение колеса поменялось на 224 единицы, что равно 56 оборота, что равно 7 об/сек - оно наверное умеет так быстро крутиться, но по словам пилотов оно стояло на месте - тогда получается глюк датчика...

на дребезг в классическом понимании (когда значение скачет туда сюда) не похоже. вот график за эти 8 секунд. как будто просто крутят колесо, целенаправлено
<img width="573" alt="screen shot 2018-11-21 at 00 11 18" src="https://user-images.githubusercontent.com/1931079/48803069-ff6f7b80-ed21-11e8-9b9c-d4f900c6716a.png">

**Comment by ponemetski** [comment]
готово,
добавил игнорирование кручения колеса триммера в течение 3-ех секунд после того как им управляли с кнопок на штурвале либо автопилот

**Comment by ponemetski** [comment]
1) добавил рэйнж для значения ручного кручения колеса чтобы не улетало в -2000
2) добавил параметр в конфиг (если такой строки в конфиге нет то при повороте колеса руками триммер будет меняться значение, как будто строка = 1)
```ini
# tq stab trim manual control, 0 - disabled
hwtf.stabtrimwheel.enabled = 1
```

**Comment by soitanen** [comment]
ок, ждем перешивки в Нск и Мск
