### ISSUE TITLE
LNAV режим roll

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#16]
Нужно описание режима. Я так понимаю что мы ищем курс которым надо лететь на следующую точку маршрута и кормим этим курсом функцию определения положения штурвала

**Comment by soitanen** [comment]
Не совсем. У нас есть маршрут из точек. к примеру у нас сегмент из А в Б. Есть линия, соединяющие эти точки. самолет понимает, где он находится и пытаеся выйти на эту линию, т.е. не просто к Б летит. Т.е. величина бокового удаления и темпа его изменения в итоге дает нам курс (похоже на ВОР или ЛОК, просто на входе не угловой параметр, а живое расстояние)

**Comment by ponemetski** [comment]
look at #56
