### ISSUE TITLE
Надпись NO V SPD

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#160]
Должен выводиться флаг NO V SPEEDS по сценарию из ФКОМ:
Displayed when the aircraft is on the ground and both V1 (decision speed) and VR
(rotation speed) are not valid or are set to less than 80 knots.

**Comment by ponemetski** [comment]
готово, достаточно обновить только GC

**Comment by soitanen** [comment]
у тебя сейчас сделано, что исчезает если внесены В1 ИЛИ ВР, а должно быть В1 И ВР, только тогда исчезнет.

Второй момент, чисто визуальный. Может в линуксе у меня криво, но нет прмежутка между NO и VSPD. Вот крупная фотка с самолета.
![image](https://user-images.githubusercontent.com/2819664/51562476-f3777580-1e9a-11e9-9c3e-7e13e5aee24b.png)

**Comment by ponemetski** [comment]
fixed

**Comment by soitanen** [comment]
работает

**Comment by soitanen** [comment]
блин, сразу после посадки вылезает надпись, прямо на касании, а должна вылезать тогда, когда стирается вся инфо из CDU на торможении, после 60 узлов. Я открою эту issue, но может это в какую-то другую. Причем я все скорости занем перед взлетом, т.е. не из воздуха стартовал. Кстати, получается что при старте с 10й мили тоже надо предусмотреть, что не вылезет надпись эта на касании.

**Comment by ponemetski** [comment]
временно добавил проверку при которой надпись горит только по граунд спид ниже 50

**Comment by ponemetski** [comment]
see:
https://github.com/ponemetski/extrinofms-issues/issues/167#issuecomment-457253805
