### ISSUE TITLE
не рабоает MCP SPD после заброса на 10 милю

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#161]
Чтобы не забыть
кидаем на 10 милю, arm autothrottle, SPEED - на PFD написано MCP SPD, но обороты на малом газу.

**Comment by ponemetski** [comment]
> сейчас если мы вводим на земле корректно Н1 лимит, то CduN1Calculated = ххх?

> если просто ничего не вводим и жмем тогу, то CduN1Calculated = хх автоматически по параметрам за окном

> и вот добавляем проверку, что если мы в воздухе и CduN1Calculated = 0, то срочно пересчитать это значение по табличке CLB=CRZ по текущим параметрам за окном

**Comment by ponemetski** [comment]
ЕСЛИ a/t армирован И режим = --- И максН1 = 0 И в_воздухе 
ТО максН1 = 92
