### ISSUE TITLE
мертвая зона по крену и тангажу

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#165]
Из Москвы просят добавить возможность задать мертвую зону по тангажу. У нас же уже есть код на педали, можно сделать аналогичный на крен и тангаж? по дефолту сделаем зону 0, а на каждом тренажере от степени убитости пружинного загружателя можно будет поставить свой нужный процент

**Comment by ponemetski** [comment]
добавил нулевые зоны для `elevator.zerozone`, `aileron.zerozone`, `tiller.capitan.zerozone`, `tiller.firstofficer.zerozone`

`hwtf.rudder.zerozone` название опции оставил как есть, просто переместил её в конфиге пониже, поэтому старый конфиг будет работать

```ini
# yokes zero zeone (percents), 0 - disabled
elevator.zerozone = 0
aileron.zerozone = 0
hwtf.rudder.zerozone = 3
tiller.capitan.zerozone = 0
tiller.firstofficer.zerozone = 0
```

пример можно посмотреть в `config.default.txt`

**Comment by soitanen** [comment]
работает.
