### ISSUE TITLE
Переход из ручной тяги в автоматическую

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#17]
Разобраться с переходом из ручной тяги в автоматическую, чтобы не было резких изменений тяги. Скорее всего нужно будет писать текущее положение рычагов и оборотов в TargetN1 и интегральный компонент положения рычагов, чтобы регулятор начинал работать с них, а не с нуля.

**Comment by ponemetski** [comment]
Собственно вопрос:
Как увидеть ситуацию с интегратором из самого верхнего коммента?

Как я понимаю у нас только рамка интегралом высчитывается, основной ход рычагов - по таблице. Поэтому проблемы с интергатором как-будто не должно быть.

**Comment by soitanen** [comment]
Ситуация простая. Взлетаем, ставим высоту например 3000, нажимаем ТОГА, тяга будет взлетная. Предположим, что хорошо выдерживаем скорость тангажом. Подходим к высоте, активируется ALT ACQ, автоматически активируется MCP SPD по тяге и в этот момент РУДы начинают уходить сильно вниз, а потом подходить к нужной тяге. Это происходит из-за того, что режим у нас еще не был активен, и _iasIntegral, который в итоге является основополагающим в TargetN1 равен 0. В итоге таргетН1 тоже сначала равен своему минимуму, а потом начинает расти. Надо при активации режима в этот интеграл принудительно записать текущие обороты, чтобы он от них начинал изменять тягу.
