### ISSUE TITLE
Flaps/Slats

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#174]
FCOM стр 1423

У нас вопрос по slats: пока не нашли галку или датареф которая меняет slats, похоже что slats меняются в модели от изменения flaps

**Comment by ponemetski** [comment]
мы будем рулить через единую галку flaps handle (которая у нас DataFlapsCommand) 
количество положений будет не 4 а больше (дл якождой комбинации flaps и slats по положению)

**Comment by sheenm** [comment]
в коде я сейчас сделал 6 положений (
0 - 0
1f - 0.2
1 - 0.4
2 - 0.6
3 - 0.8
full - 1

**Comment by sheenm** [comment]
| Позиция flaps | В float | flaps, deg | slats, deg |
|---------------|---------|------------|------------|
| 0             | 0       | 0          | 0          |
| 1             | 0.2     | 0          | 18         |
| 1f            | 0.4     | 10         | 18         |
| 2             | 0.6     | 15         | 22         |
| 3             | 0.8     | 20         | 22         |
| Full          | 1       | 35         | 27         |

**Comment by ValeriM** [comment]
Можно меня отписать от этих оповещений?
