### ISSUE TITLE
Кнопки отключения A/P и A/T должны отключать при нажатии а не при отпускании

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#176]

**Comment by soitanen** [comment]
сюда же отключение сирены невыпущщеного шасси, кнопка gear horn cutout (которая на блоке РУД). Правда из-за глюка, что loop играется до конца, не совсем ясно - то ли кнопка не отключает, то ли звук еще долго играется.

**Comment by ponemetski** [comment]
переделал
- отключение автопилота
- отключение автомата тяги
- отключение сигнализации шасси было уже по нажатию, я добавил форсированную останоку звука (не уверен на 100% что заработает)

**Comment by soitanen** [comment]
да, правильно
