### ISSUE TITLE
Добавить форсированную остановку looped звуков

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#179]

**Comment by soitanen** [comment]
по идее не только его, но любых loop sound. Когда отпускаешь на земле тест stall warning или mach overspeed, то тоже ожидаешь моментально прекращение звука, но оно все равно продолжает звучать

**Comment by ponemetski** [comment]
предлагаю делать форсированную остановку группами звуков, потому что так безопаснее с точки зрения глюков и в итоге получим остановку только тех звуков которые реально должны уметь так

**Comment by ponemetski** [comment]
некоторая информация:
- SoundStallWarn и SoundClacker когда он работают по условиям скорости (это у нас в pfd коде) уже умеют принудительно прерываться
- SoundStallWarnTest1/2 и SoundMachAirspeedTest1/2 которые работают при нажатии кнопок на оверхеде я пофиксил только что, можно проверять

**Comment by soitanen** [comment]
пока вроде все ок
