### ISSUE TITLE
Коэффициенты в режиме VOR

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#18]
Кусок из файла config.txt
```
# Vor -> hdg
# driftAng = magHdg - magTrack
# deltaTargetHeading = range(driftAng + dataNavLoc * ApVorModeP + _locRate * ApVorModeD, -30, 30)
system.config.ApVorModeP = 100
system.config.ApVorModeD = 600

# Loc -> hdg
# driftAng = magHdg - magTrack
# deltaTargetHeading = range(driftAng + dataNavLoc * ApLocModeP + _vorRate * ApLocModeD, -30, 30)
system.config.ApLocModeP = 12
system.config.ApLocModeD = 60
```
- [x] вижу перепутанные входные данные (_vorRate и _locRate), по идее расчет один и тот же, но нет ли перепутки в коде?

- [x] второй момент - надо будет писать динамически меняющийся коэффициент по VOR маяку в зависимости от удаления - слишком большая разница вблизи и вдалеке. Точную формулу скажу чуть позже.

**Comment by ponemetski** [comment]
по перепутанным проверил - в коде все верно, ошибка в комменте в конфиге, исправил

**Comment by soitanen** [comment]
- [ ] при пропадании синала (улетели от маяка) режим должен отключаться (т.е. либо просто пропадет директор или в автопилоте перйдет в CWS R)

**Comment by soitanen** [comment]
- [ ] надо проверить условия входа в режим. Я летел курсом 240. радиал от VOR маяка ловил 202. Луч был слева от меня больше чем на точку. Нажал кнопку VOR/LOC - режим не парясь активировался
- [ ] не могу понять по подрежиму, когда мы уже на луч вышли. там rollRate ограничивается до 1.3 град/сек, это вроде есть, но угол крена тоже должен быть ограничен до 8 градусов.

**Comment by soitanen** [comment]
| 10 | 15 | 20 | 25 | 30
-- | -- | -- | -- | -- | --
100 | 0.11 | 0.07 | 0.05 | 0.04 | 0.03
120 | 0.16 | 0.1 | 0.08 | 0.06 | 0.05
140 | 0.22 | 0.14 | 0.11 | 0.08 | 0.07
160 | 0.28 | 0.19 | 0.14 | 0.11 | 0.09
180 | 0.36 | 0.24 | 0.17 | 0.14 | 0.11
200 | 0.44 | 0.29 | 0.21 | 0.17 | 0.14
220 | 0.54 | 0.35 | 0.26 | 0.2 | 0.16
240 | 0.64 | 0.42 | 0.31 | 0.24 | 0.19
260 | 0.75 | 0.49 | 0.36 | 0.28 | 0.23
280 | 0.87 | 0.57 | 0.42 | 0.33 | 0.27
300 | 1 | 0.66 | 0.48 | 0.38 | 0.3
320 | 1.13 | 0.75 | 0.55 | 0.43 | 0.35
340 | 1.28 | 0.84 | 0.62 | 0.48 | 0.39
360 | 1.43 | 0.94 | 0.69 | 0.54 | 0.44
380 | 1.6 | 1.05 | 0.77 | 0.6 | 0.49
400 | 1.77 | 1.17 | 0.86 | 0.67 | 0.54
420 | 1.95 | 1.28 | 0.95 | 0.74 | 0.6
440 | 2.14 | 1.41 | 1.04 | 0.81 | 0.65
460 | 2.34 | 1.54 | 1.13 | 0.89 | 0.72
480 | 2.55 | 1.68 | 1.24 | 0.96 | 0.78
500 | 2.77 | 1.82 | 1.34 | 1.05 | 0.85
520 | 2.99 | 1.97 | 1.45 | 1.13 | 0.91
540 | 3.23 | 2.12 | 1.56 | 1.22 | 0.99
560 | 3.47 | 2.28 | 1.68 | 1.31 | 1.06

Это табличка для интерполяции. В колонках у нас ограничение крена, выставленное на панели MCP, по строкам - True Air Speed, TAS в узлах

Получаем значение из таблицы, умножаем на коэффициент 1.4 (его по хорошему в конфиг для дальнейшей настройки).

В итоге будет так:
SystemConfigApVorModeP = (DME * 2.116) / (interpolate2d(табличка) * 1.4)
В итоге настраивать можем 1.4 - это даст регулировку возможного перелета-недолета. Если VOR без DME, то SystemConfigApVorModeP = 90

**Comment by soitanen** [comment]
лечу в HDG SEL, настроен на VOR, не в зоне доворачивания. Нажиамаю кнопку VOR-LOC. HDS SEL отключился, VOR LOC не заармировался, режим стал пустой....

**Comment by soitanen** [comment]
The VOR on-course submode is active when these conditions
occur for at least 5 seconds:
 - Beam deviation is less than 1 degree
 - Course error is less than 18 degrees.

The VOR on-course submode is also active when the deviation
beam rate of change is less than 0.15 degrees per second for at
least 10 seconds.
The airplane will not bank more than 8 degrees. The maximum
roll rate is 1.3 degrees per second.

beam deviation - 1 градус равен 0.25 в X-Plane-овских единицах

**Comment by ponemetski** [comment]
В режиме захвата курсового маяка (LOC) крен до 30, а rollrate до 7

**Comment by ponemetski** [comment]
> надо проверить условия входа в режим. Я летел курсом 240. радиал от VOR маяка ловил 202. Луч был слева от меня больше чем на точку. Нажал кнопку VOR/LOC - режим не парясь активировался

    // vor/loc cases
    if (vorLoc == Armed)
    {
        int navType = state.GetInt(_dataNavType);
        if (navType == 4 || navType == 10)
        {
            // loc
            var deltaTargetHeading = LocMode(
                state.GetFloat(_dataNavLoc), 
                state.GetFloat(DataMagHeading), 
                state.GetFloat(DataMagTrack), 
                elapsedMilliseconds,
                state.GetFloat(SystemConfigApLocModeP), 
                state.GetFloat(SystemConfigApLocModeD));

            var deltaCurrentHeading = 
                _180(state.GetFloat(DataMagHeading) - state.GetInt(_mainpanelCourseOled));
            if (Abs(state.GetFloat(_dataNavLoc)) < 0.5 || 
     (Abs(state.GetFloat(_dataNavLoc)) < 2.45 && Abs(deltaTargetHeading) < Abs(deltaCurrentHeading)))
            {
                _afds.RollState = RollState.Loc;
            }
        }
        else if (navType == 3)
        {
            // vor
            var deltaTargetHeading = VorMode(
                state.GetFloat(_dataNavLoc), 
                state.GetFloat(DataMagHeading), 
                state.GetFloat(DataMagTrack), 
                elapsedMilliseconds,
                state.GetFloat(SystemConfigApVorModeP), 
                state.GetFloat(SystemConfigApVorModeD));

            var deltaCurrentHeading =
                _180(state.GetFloat(DataMagHeading) - state.GetInt(_mainpanelCourseOled));
            if (Abs(state.GetFloat(_dataNavLoc)) < 0.5 || 
     (Abs(state.GetFloat(_dataNavLoc)) < 2.45 && Abs(deltaTargetHeading) < Abs(deltaCurrentHeading)))
            {
                _afds.RollState = RollState.Vor;
            }
        }
    }

**Comment by soitanen** [comment]
**вопрос правильно ли что они оба по почти одинаковым условиям активируются?**
Да, суть примерно одинаковая. Другая ширина луча VOR маяка просто требует другого коэффициента

**Comment by ponemetski** [comment]
теперь у параметра конфига новое значение 

    # Vor -> hdg
    # driftAng = magHdg - magTrack
    # p = (dme * 2.116) / (Interpolate_2d(tbl, bankLimit, tas) * systemConfigApVorModeP)
    # p = 90 if no DME
    # deltaTargetHeading = range(driftAng + dataNavLoc * p + _vorRate * ApVorModeD, -30, 30)
    system.config.ApVorModeP = 1.4
    system.config.ApVorModeD = 60

**Comment by ponemetski** [comment]
в этом таске вроде как все закрыто, надо будет как то систематизировать найденные проблемы потому что здесь много и разрозненно - тяжело воспринимать

**Comment by soitanen** [comment]
тоже предлагаю это пока закрыть. будут вылезать баги - буду создавать отдельные issue, а так вроде пока все работает как надо.
