### ISSUE TITLE
Переход курса через 0 вызывает проблемы на PFD

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#180]
- [x] с ромбом глиссады (указатель вертикали)
- [x] с директором по крену 

есть два видео с описанием проблемы, здесь не выкладываю

**Comment by ponemetski** [comment]
_забавно что номер этой issue 180..._

с директором по крену не понятно

его положение на пфд вычисляется по формуле
`(dataRollDeg - gcPfdFdRoll) * 50px`
dataRollDeg - текущий крен из иксплейна
gcPfdFdRoll - целевой крен по расчетам флайт директора

причем gcPfdFdRoll может быть в пределах от -30 до +30 градусов, банк лимит

основные мои подозрения падают на фильтр который фильтрует нам целевой крен (он же gcPfdFdRoll) - фильтрует он с коеффицентом 0,1 - то есть новое значение дает 10% к итогу - то есть довольно плавно 

хотя возможно это логика расчета целевой крена дает какой то сбой и резко командует вместо 0 новое значение -30 а потом плавно его доводит до нуля

в идеале завтра поработать над этим багом потому что у меня не воспроизволится 

вопрос по тангажу: получится ли такое же поймать по тангажу?

**Comment by ponemetski** [comment]
проблема была в том что разница курсов в режимах VOR / LOC / LNAV не нормализовалась в диапазоне от -180 до +180
из-за этого директор улетал в лимит по банк углу

**Comment by soitanen** [comment]
работает
