### ISSUE TITLE
Коэффициент по тангажу

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#19]
Подбирал сегодня коэффициенты.
Для тангажа невозможно в принципе подобрать для всех режимов. Нужна будет табличка.

```
# _pitchIntegral += pitchRateErr * ApPitchModeI / elapsedMilliseconds
system.config.ApPitchModeI = 0.3 
# apPitchCmd = pitchRateErr * ApPitchModeP + _pitchIntegral
system.config.ApPitchModeP = 0.4
```

Это сейчас. В табличку запихнем ApPitchModeI

Скорость по прибору | ApPitchModeI
---- | ----
140 | 0.7
280 | 0.3
340 | 0.05

Возможно, что потом их тоже придется немного регулировать.
Пропорциональный вроде не требуется так менять.

**Comment by ponemetski** [comment]
етсь ли у нас забросы по тангажу?
нужно попробовать воспользоваться новым расчетом рэйт, может это решит проблему?

**Comment by soitanen** [comment]
новый рэйт эту проблему не решит 100%, тут физика процесса другая

**Comment by ponemetski** [comment]
в **дополнение** к старому формату

    system.config.ApPitchModeI = 0.3

добавлен новый формат

    system.config.ApPitchModeI = 140: 0.7, 280: 0.3, 340: 0.05

есть особенность динамического регулирования.
если моя программа видит что задано значение в новом формате, то она записывает его в таблицу и дальше динамически менять его нельзя
но
можно на ходу поменять формат на старый и моя программа начнет работать с задаваемым значением
после этого можно вновь задать значение в новом формате (можно уже другое) и программа прочитает и начнет использовать его

**Comment by ponemetski** [comment]
если нужно в качестве скорости НЕ DataVIndKias напиши какую нужно

**Comment by soitanen** [comment]
Проверил - работает. Ничего не раскачивается теперь.
