### ISSUE TITLE
Перестановка самолета и режим автопилота

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#20]
Сейчас, по крайней мере у меня на компе, если я в Х-Плане переставляю самолет, но если у меня был включен автопилот, то он и остается в таком же режиме при начале новго полета - это приводит к тому, что самолет может начинать улетать категорически куда-то не туда. Предлагаю при перестановке самолета просто проверять физическое положение переключателей (директора, например), оставлять в окошках те же значения, что и были раньше, но все режимы по тангажу, крену, автопилоту - выключить. Максимум что у нас получится - заармируется автомат тяги, потому что, например, тумблер оставим в положении ARM. А потом уже в зависимости от задачи включаем требуемые режимы.

**Comment by ponemetski** [comment]
есть параметр DataTotalFlightTimeSec - это галка 1-2 (missn time) время полета
когда это время сбрасывается в ноль я вижу что самолет переставили или разбили
при этом я пишу "FmsBrige systems reinitialized" в лог
при этом должны сбрасываться все режимы автопилота

если пользоваться Location - Local map то сброса не происходит
а если переставить на 3 мили или в другой порт то сброс происходит

**Comment by soitanen** [comment]
Да, мой косяк, галка №1 не стояла.
