### ISSUE TITLE
Фильтр для DataIasRate 

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#21]
чтобы не было такой картины 

![image](https://user-images.githubusercontent.com/1931079/33216089-7b48ebc0-d143-11e7-921d-76bc55ee86fe.png)

**Comment by soitanen** [comment]
Берем вот эту статью.
http://copterpilot.ru/articles/osnovy-sglazhivaniya-i-filtracii-dannyx-eksponencialnoe-srednee/
Делаем ту формулу, которая там описана, если поставить коэффициент альфа=0.15, то получим сглаживание как на картинке.
Возможно, что вместо средней скорости за последнюю секунду avrIas надо будет применить подобный фильтр. Надо будет собрать набор данных и не нем подобрать коэффициент.
![image](https://user-images.githubusercontent.com/2819664/33216530-48a3bd56-d145-11e7-991c-e8b62ff4b910.png)

**Comment by ponemetski** [comment]
решили, теперь берем дельту Т из сима
