### ISSUE TITLE
Автомат тяги и значение скорости

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#23]
Ситуация: лечу в воздухе. Автомат тяги армирован, но не активен, твоя программа перезапущена, никаких активных режимов нет. Активирую режим вертикальной скорости, автоматически активруется автомат тяги в режим MCP SPD (это правильно), но почему-то текущая скорость не записывается как заданная, а должна, так как никакой режим по скорости в данный момент не активен.

**Comment by ponemetski** [comment]
При активации MCP SPD в автомате тяги он должен смотреть, а не было ли активного реждима по поддржанию скорости, т.е. TOGA, MSP SPD PITCH, VNAV SPD, VNAV PTH (VNAV вообще отдельная тема), и если не было, то текущую скорость вписать в заданную

**Comment by ponemetski** [comment]
активация режима VS, ALT HOLD, ALT ACQ, GS - должна приводить к активации MCP SPD в автомате тяги, если он был заапмирован.

**Comment by soitanen** [comment]
- [ ] MCP SPEED в автомате тяги сейчас в любом случае стал записывать текущую скорость как заданную, независимо от предыдущего режима.
