### ISSUE TITLE
LVL CHG лампочка

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#24]
При активном режиме MCP SPD по тангажу должна гореть лампочка на кнопкке LVL CHG.

**Comment by soitanen** [comment]
На веб-морде горение лампочки не наблюдаю...

**Comment by soitanen** [comment]
PitchState == PitchState.VS - видио все-таки должно быть MCP SPEED, а не VS?

**Comment by ponemetski** [comment]
поправил

    state.Set(MainpanelLvlChgLed, PitchState == PitchState.McpSpeed);

**Comment by soitanen** [comment]
Работает.
