### ISSUE TITLE
ALT ACQ и изменение высоты

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#25]
При активированном режиме ALT ACQ если я начал менять высоту на MCP, то ALT ACQ должен отмениться и перейти в V/S с присвоением текущей вертикальной скорости в качестве заданной. Сейчас остается активным ALT ACQ и самолет ведет себя неправильно

**Comment by ponemetski** [comment]
включаем 
- AT McpSpeed
- Pitch VS
- окошко вертикальной скорости заполняем текущей округленной

**Comment by soitanen** [comment]
работает
