### ISSUE TITLE
Go Around и значение скорости на PFD

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#26]
Сейчас при нажатии кнопки TOGA при уходе на второй круг исчезает значение заданной скорости на PFD. Это неправильно. Скорость должна исчезнуть только на MCP. На PFD заданная скорость отображается всегда. Кстати, при режиме VNAV будет то же самое - заданная скорость всегда есть на PFD, но окошко MCP SPD будет пустым.

**Comment by ponemetski** [comment]
Баг исправляется просто но долго.
Предлагаю заодно совместить его исправление с прописыванием скорости в махах.

Есть информация

<img width="608" alt="screen shot 2017-11-30 at 12 41 46" src="https://user-images.githubusercontent.com/1931079/33424124-e2676b7e-d5cb-11e7-8707-d84e68af7bb6.png">

<img width="592" alt="screen shot 2017-11-30 at 12 38 02" src="https://user-images.githubusercontent.com/1931079/33424013-910e1d4a-d5cb-11e7-9f35-9d000e70d2e1.png">
и далее из этой презентации

Есть вопросы:
- где в иксплейне брать значения в махах?
- по какой именно высоте переключаться?
- показываем ли на ПФД значение заданной скорости в махах?
- по какой формуле переводить чтобы на ленте скорости показать маркер в нужном месте?
- какие то еще особенности использования?

**Comment by soitanen** [comment]
- [ ] значение текщей скорости в М - 4-0
- [ ] у Энрико сделано 26500. Какой-то другой точной цифры я не встречал, предлагаю так и оставить
- [ ] описание функции кнопки в AMM - When you push this switch and the airspeed is more than mach
0.6, it changes the display from IAS in knots to mach or from mach to IAS in knots. If the airspeed is less than mach 0.6, the display will only show knots and the change over switch does not do anything.
- [ ] на PFD вместо заданной скорости в узлах появляется скорость в Махах, видно на фотографиях дисплеев
![image](https://user-images.githubusercontent.com/2819664/33425197-07e32e58-d5cf-11e7-8a46-dac0a1bf7634.png)
- [ ] нужна из симулятора текущая скорость звука - 6-4. Она определяется в узлах. Мой код по работе кнопки:
```# Changeover button
var changeover_button_press = func {

	var a = getprop("/fdm/jsbsim/atmosphere/a-fps");
	var ias = getprop("/instrumentation/airspeed-indicator/indicated-speed-kt");
	if ( ias == nil ) ias = 0.001;
	if ( ias < 1 ) ias = 100;
	var tas = getprop("/instrumentation/airspeed-indicator/true-speed-kt");
	if ( tas == nil ) tas = 0.001;
	if ( tas == 0 ) tas = 0.001;

	if (getprop("/autopilot/internal/SPD-IAS")) {
		var target_ias = getprop("/autopilot/settings/target-speed-kt");
		var target_mach = math.round((target_ias * tas/ias) / ( a * 0.5924838012959), 0.01);
		if (target_mach < 0.60) {}#target_mach = 0.60;
		else {
			if (target_mach > 0.89) target_mach = 0.89;
			
			setprop("/autopilot/settings/target-speed-mach", target_mach);

			setprop("/autopilot/internal/SPD-IAS", 0);
			setprop("/autopilot/internal/SPD-MACH", 1);
		}
	} else {
		var target_mach = getprop("/autopilot/settings/target-speed-mach");
		var target_ias = math.round((target_mach * ias * a * 0.5924838012959) / tas, 1);
		if (target_ias > 399) target_ias = 399;
		if (target_ias < 100) target_ias = 100;
		setprop("/autopilot/settings/target-speed-kt", target_ias);

		setprop("/autopilot/internal/SPD-MACH", 0);
		setprop("/autopilot/internal/SPD-IAS", 1);
	}
}
```
Единственный момент, что у меня a - это футы в секунду, а X-Plane дает узлы. Надо одно в другое перевести.
- [ ] для отображения маркера скорости в нужном месте. Таргет_спид_УЗЛЫ = (target_speed_mach * ias_kt * a_fps * 0.5924838012959 ) / ( TAS_KT)
Я так прикинул, что 0.5924838012959 - это коэффициент переводящий футы в секунды в узлы. Т.е. ты скорее сего просто будешь брать скорость звука сразу в узлах, а коэффициент этот сложный превратится в 1

**Comment by soitanen** [comment]
- [ ] предугадывая возможные приколы, предлагаю сразу добавить резервный автоматический переход из инидкации в Махах обратно в узлы, если наша скорость становится ниже чем 0.58М.

**Comment by ponemetski** [comment]
все сделал, проверил в иксплейне, работает

**Comment by soitanen** [comment]
вроде все ок
