### ISSUE TITLE
Посадка на двух автопилотах

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#27]
> Камиль Михаил, [Nov 30, 2017, 11:59:53 AM]:
> потому что мы не писали логику двух автопилотов, автоматическую посадку мы пока на одном сделал
> 
> Alexander Ponemetski, [Nov 30, 2017, 11:59:53 AM]:
> он у нас вообще никогдв не армируется в коде
> 
> Камиль Михаил, [Nov 30, 2017, 12:00:44 PM]:
> я почитал внимательно документы, пишут, что он сядет и на одном, но при таком случае у него режим FLARE сработает, но не будет зеленым на FMA, то есть там так и останется G/S
> 
> Alexander Ponemetski, [Nov 30, 2017, 12:00:56 PM (11/30/17, 12:01:17 PM)]:
> можешь описать в issue? я буду делать на одном но все что нужно будет гореть как будто на двух садимся
> 
> Камиль Михаил, [Nov 30, 2017, 12:02:43 PM]:
> а вот при двух автопилотах он заармируется. там еще прикол есть со стаблизатором... но да. надо будет подробно написать

- [x] делаем так, что если лампа горит или уже захвачено - подключаем другой автопилот. Если не выполняются эти условия - переключаем на другой автопилот.
- [x] Ниже 800 футов второй автопилот подключить уже нельзя. Проверяем по радиовысотомеру.

- [x] Когда захвачен курсовой маяк, то надпись CMD меняется на SINGLE CH янтарного цвета,.. Если летели в директорном режиме - надписи не будет.
- [x] Через 10 секунд после активации SINGLE CH сменится на простой зеленый CMD, а на FMA в разделе про тангаж заармируется FLARE.
- [x] Retard: если на FMA есть слово FLARE - то 27 футов. Если слово FLARE отсутствует (автопосадка на одном автопилоте или заход в директорном режиме), то 24 фута

- [x] при заходе на двух автопилотах на высоте 350 футов стабилизатор автоматически откручивается "на себя" (т.е. в плюс к имеющемуся значению) на 1.5 юнита.
- [x] ниже 400 футов по РВ автотриммирование не работает.

- [x] после касания экипаж обязан отключить автопилот. Индикация на FMA сменится: FLARE исчезнет и опять появится G/S. При этом пофиг, что директоров нет, индикация все равно есть.

- [x] выход из режима двух автопилотов кнопками CMD 
- [x] выход из автопилота нажатием кнопок на штурвале и тумблер на MCP (базовая версия)

- [x] Если был подключен один автопилот - то надатие кнопки ТОГА его отключает
- [x] Если было включено оба - то самолет уходит сам. 
- [x] Выход из режима двух автопилотов к одному произойдет при выключении режима G/A в какой-либо другой режим по тангажу.

**Comment by soitanen** [comment]
Итак про два автопилота.
В обычной ситауции, когда мы летим с включенным автопилотом, нажатие на кнопку другого автопилота приведет к переключению на тот автопилот. Первый при это выключится. Однако, если у нас армирован режим Approach или уже захвачены курсовой и глиссадные маяки, то нажатие на кнопку второго автопилота зажжет в нем лампу и готовность к подключению для полностью автоматической посадки. Ниже 800 футов второй автопилот подключить уже нельзя. Проверяем по радиовысотомеру.

- [ ] Т.е. делаем так, что если лампа горит или уже захвачено - подключаем другой автопилот. Если не выполняются эти условия - переключаем на другой автопилот.
- [ ] При подключении второго автопилота надо запомнить, какой автопилот был мастером. В случае ухода на второй круг, когда один автопилот отключится, мастером останется тот же, что и был до подключения второго автопилота.

Когда захвачен курсовой маяк, то надпись CMD меняется на SINGLE CH янтарного цвета, то сигнализирует пилоту о том, что сам самолет не сядет, надо будет отключать автопилот. Если летели в директорном режиме - надписи не будет.
Переключение надписи из SINGLE CH в CMD произойдет при соблюдении неоткорых условий. У нас есть режим LOC-ON-COURSE. Есть еще один режим, никак не влияющий на полет, но влияющий на индикацию. Называется APPROACH-ON-COURSE. Он становится активным если мы LOC-ON-COURSE == 1 AND PitchState==GS AND RadioAltimeter < 1500 ft. Запоминаем время активации этого режима. Через 10 секунд после активации SINGLE CH сменится на простой зеленый CMD, а на FMA в разделе про тангаж заармируется FLARE.
В самолете сделано так, что если подключены два автопилота, но FLARE по каким-то причинам не заармировался, то на высоте 350 футов по РВ оба автопилота отключаются.

Теперь про прикол со стабилизатором.
при заходе на двух автопилотах на высоте 350 футов стабилизатор автоматически откручивается "на себя" (т.е. в плюс к имеющемуся значению) на 1.5 юнита. Руль высоты, соответственно, отклоняется на пикирование, чтобы противодействовать отклонению стабилизатора. Но помнишь, мы делали модуль, который сам триммирует самолет? Я у себя в модели сделал так: ниже 400 футов по РВ автотриммирование не работает. Тогда получается, что самолет открутил стабилизатор на 1.5 юнита, а руль будет нормально бороться с ним. На взлете все равно ниже этой высоты включать АП нельзя, на заходе все равно к 500 футам заход должен быть стабилизирован, а значит и триммировать уже не придется.

На посадке после касания экипаж обязан отключить автопилот. Индикация на FMA сменится: FLARE исчезнет и опять появится G/S. При этом пофиг, что директоров нет, индикация все равно есть.

Теперь прикол про уход на второй круг.
Если был подключен один автопилот - то надатие кнопки ТОГА его отключает и уходить нужно на руках.
Если было включено оба - то самолет уходит сам. Выход из режима двух автопилотов к одному произойдет при выключении режима G/A в какой-либо другой режим по тангажу.

Пока вроде все. Буду что-то вспоминать - допишу.

**Comment by ponemetski** [comment]
вопросы
1) "делаем так, что если лампа горит или уже захвачено - подключаем другой автопилот." имеется в виду лампа на кнопке APP?
2) "Когда захвачен курсовой маяк, то надпись CMD меняется на SINGLE CH" курсовой маяк - это только VOR?
3) "У нас есть режим LOC-ON-COURSE."  у нас только `vorOnCourse = (Abs(navLoc) < 0.5) && Abs(_180(course - magTrack)) < 5` это одно и тоже или нет?
4) "Через 10 секунд после активации SINGLE CH сменится на простой зеленый CMD" это только если уже включили второй автопилот, если не включили то так и будет гореть SINGLE CH, верно?

**Comment by soitanen** [comment]
1. Да.
2. Наоброт, только LOC. Причем SINGLE CH будет гореть только если кнопка APP была нажата, т.е. армирован или активен режим GS. Если просто в VOR/LOC - то продолжит гореть CMD.
3. Не совсем. Вот выдержка из АММ:
Localizer on course occurs when these conditions are valid:
- Localizer deviation is less than 0.8 degrees (откуда брать это в градусах - не очень понятно. давай примем также 0.5 точки)
- Beam rate is less than 0.045 degrees/second
- Bank angle is less than 6 degrees.
Localizer on course also occurs for these conditions:
- The localizer was in the capture mode for more than 135
seconds
- The localizer deviation is less than 0.8 degrees.
4. Да, конесно.

**Comment by ponemetski** [comment]
Еще вопросы:
1) режим pitch Flare у нас активируется если у нас активен режим pitch GS и радиовысота меньше 50. нужно ли добавить сюда "и включены два автопилота"?
2) режим a/t Retard активируется (в том числе и) когда мы находимся в режиме pitch Flare и радиовысота меньше 24. Если ответ на предыдущий вопрос "да", то не сломаем ли мы описанную здесь активацию a/t Retard?
3) как, отключить режим захода на двух автопилотах **до** посадки?
4) как, отключить режим захода на двух автопилотах **после** посадки?

**Comment by soitanen** [comment]
1. Тут тема такая. Что если 2 автопилота включены, то он активируется и появляется надпись на FMA - FLARE. В документах написано, что если летишь на одном автопилоте, то ты должен отключить автопилот до высоты 50 футов. Но в сервисных документах уже написано, что даже один автопилот все равно активирует режим FLARE и посадит его. Но при этом на FMA останется индикация G/S и не будет прикола с откручиванием стабилизатора на высоте 350 футов.
2. А я не знаю как у тебя этот момент написан, это к вопросу сломаем или нет? Предлагаю сделать так, что если на FMA есть слово FLARE - то 27 футов. Если слово FLARE отсутствует (автопосадка на одном автопилоте или заход в директорном режиме), то 24 фута и плюс-минус в глиссаде.
3. Оба автопилота выключить, оба директора выключить. Или перенастроить одну из радиостанций на что-то отличное от того, куда садимся. Или нажать кнопку ТОГА. Вообще в FCOM или в AMM есть весь этот перечень.
4. Примерно аналогично тому что в пункте 3. Самолету по большому счету пофиг, что он в воздухе или на земле, вычислитель что-то там считает. Просто после посадки они рулят, у них могут гореть на FMA индикация VOR/LOC & G/S. Потом прирулят, выключат директора - так и отключится.

**Comment by ponemetski** [comment]
> Камиль Михаил, [Dec 8, 2017, 10:57:42 AM]:
> Это про активацию режима retard
> 
> В директором режиме это не имеет смысла - режим работает только ниже 50 футов, а ниже 50 футов директора не показывают
> 
> На fma останется только G/S и Vor/loc
> 
> В общем слово flare на fma появляется только с двумя автопилотами

**Comment by ponemetski** [comment]
> Про отключение автопилота: нажать цмд? Если оба горят то любой который нажат отключится

**Comment by soitanen** [comment]
Глюки
- [ ] летим. жмем APP. захватываем курсовой. глиссадный пока еще нет. жмем кнопку второго автопилота. У нас заармирован GS. В момент захвата GS он становится и активным (зеленым) на FMA, но и продолжает висеть в белом заармированном цвете
- [ ] откручивание стабилизатора на 350 футах. оно не должно быть резким, а должно происходить с нормальным темпом.

**Comment by soitanen** [comment]
глюк с неразармированием GS проявился и на одном автопилоте

**Comment by soitanen** [comment]
еще момент. после посадки надо отключить автопилот кнопкой на штурвале, например. Индикация FLARE должна исчезнуть и замениться на G/S.

**Comment by soitanen** [comment]
ок
