### ISSUE TITLE
THR HLD поменять высоту активации

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#28]
не знаю где нашел я цифру 400, но правильная цифра 800 для переключения режима  в ARM. Прошу исправить. На самом деле берется барометрическая высота, берется высота аэродрома, и эти 800 футов расчитываются по барометрическому выосотомеру. Та же самая фигня потом всплывет при активации режимов уменьшения тяги и начала разгона в FMC. Пока мы не умеем брать высоту аэродрома из базы данных можно сделать заглушку - в момент нажатия ТОГА текущая высота на высотомере записывается в переменную значения высоты аэродрома взлета. Если оставим радиовысотомер, как сейчас - то будет вылезать фигня в горных аэропортах.

**Comment by soitanen** [comment]
Да, ещё там прочитал - не 18 секунд, а 10. Мне далее самому очень интересно стало, где я нашел 400 и 18. Возможно, что это было на 737 Классике, я изначально для неё автопилот делал, а по NG документация ищется сложнее, вот я и перенес некоторые вещи, не найдя нужных данных.

**Comment by ponemetski** [comment]
у меня есть высота аэропорта например для ULLI это 00079 футов над уровнем моря
могу брать ее

1) что делать если аэропорт вылета не указан? 

у меня непонимание

    // DataAltFtMsl 20-2
    // DataSlPressInHdg 5-0
    baroIn = 29.92f;
    pressAlt = state.GetFloat(DataAltFtMsl) 
             + InToHpa(baroIn - state.GetFloat(DataSlPressInHdg)) * 27.3;
    state.Set(DataPressAltitude, (float)pressAlt);

есть вот такой код - вычисляет высоту при стандартном давлении

есть просто переменная их икс-плейна

    DataAltFtMsl (галка 20-2) // раньше называли  DataBaroAltitude

2) что показывает DataAltFtMsl? в данном случае мы берем ее?

**Comment by soitanen** [comment]
0. Да, 79 футов это и есть как раз превышение аэропорта Пулково.
1. Я думаю, что сделаем так. Тренажер-то развлекательный, поэтому иногда будут взлетать с автоматом тяги, но с неуказанным аэропортом вылета. Если аэропорт не указан, то берем текущую выысоту на барометрическом высотомере как высоту аэродрома. А если указан - то она задана у нас.
2. DataAltFtMsl показывает высоту объекта (самолета точнее) над уровнем моря без всяких приколов с давлением и рельефом. В данном issue нужно сделать другое. Самолет же будет смотреть на высотомер, у него нет другого средства измерения. Соответсвенно то что было в окошке высотомера в момент нажатия кнопки ТОГА - записалось в переменную (или там уже что-то было, например 79 футов для Пулково). Взлетаем. Когда на барометрическом высотомере, с учетом коррекции по давлению (т.е. именно та цифра, которая пилоту и показывается) станет 879 футов или выше и при этом уже больше 10 секунд в воздухе - отключаем THR HLD и переводим в ARM

**Comment by soitanen** [comment]
работает
