### ISSUE TITLE
Продолжающееся интегрирование на паузе

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#29]
Если ставим симулятор на паузу, то автопилот не должен продолжать считать положение рулей и стабилизатора, а то я пока стоял на паузе, он там наинтегрировал хрен пйоми что и после выхода из паузы я улетел в космос

**Comment by ponemetski** [comment]
Первая попытка починить проблему, теперь в паузе вся логика моей программы (вся та что отвечает за самолет) не запускается.
Нужно активно проверять.

**Comment by soitanen** [comment]
Проверил пока в двух вариант - тупо нажать паузу - перестает двигать рули и стабилизатор. Второй вариант - уйти в настройки погоды, или местоположения - тоже перестает двигать рулями. Т.е. на данный момент все ОК. Закрываю.
