### ISSUE TITLE
Поймал ошибку деармирования VS

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#30]
Летим в ALT HOLD стабильно. Накручиваем на МСР новую высоту. VS армируется. Теперь скручиваем обратно высоту на ту, на которой сейчас и летим - VS не деармировался, а должен.

**Comment by ponemetski** [comment]
добавил, если при проверке работает, можно закрывать

**Comment by soitanen** [comment]
Продолжается поведения как я и описал. Более подробно. лечу на высоте 2000 в режиме ALT HOLD. Накручиваю новую высоту 2500, VS в белом цвете появляется под зеленой надписью ALT HOLD. Сразу же скручиваю высоту обратно на 2000 - VS не исчезает.

**Comment by soitanen** [comment]
работает.
