### ISSUE TITLE
Директоры отображаются по одному

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#32]
- [x] в #13 остались еще:

> Еще момент: TOGA не может работать в автопилоте в принципе. Если включена TOGA и мы нажимае кнопку включения автопилота, то режим по тангажу автоматически перейдет в MCP SPD, а автомат тяги в N1 (аналог нажатия LVL CHG).

- в ней же и про CWS

> По крену ... при отключении режима TOGA, если не был выбран до этого какой-то другой режим по тангажу, то директорная стрелка по крену исчезает. Если был включен автопилот - то крен будет в режиме CWS ROLL.

- еще про CWS в #18 

> при пропадании синала (улетели от маяка) режим должен отключаться (т.е. либо просто пропадет директор или в автопилоте перйдет в CWS R)

итого:

- [x] возможность рисовать стрелки директора по одной если не выбран режим

**Comment by soitanen** [comment]
вроде тоже ок
