### ISSUE TITLE
Отключение автопилота при перенастройки радиостанции

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#33]
из комментов к #27 создал новую issue

> перенастроить одну из радиостанций на что-то отличное от того, куда садимся

вопросы:

1) в каких режимах это работает? мое предположение - только roll Loc (по pitch любой получается)
2) под радиостанциями имеются в виду NAV1 NAV2?
3) ADF1 ADF2 не учитываем, верно?
4) есть ли еще особенности отключения путем перенастройки?

**Comment by soitanen** [comment]
1. именно отключится автопилот когда уже LOC + GS. Если только LOC был в момент перенастройки - то курс перейдет в CWS
2. да
3. к ним автопилот вообще не имеет доступа
4. вроде нет

**Comment by ponemetski** [comment]
> перенастроить одну из радиостанций на что-то отличное от того, куда садимся

> именно отключится автопилот когда уже LOC + GS. 

в какие режимы по крену и тангажу перейдет при этом автопилот (ну то есть та штука которая рисует директоров)?

**Comment by soitanen** [comment]
FCOM пишет, что отключение режима произойдет при перенастройке радиостанции. т.е. поменяли частоту - оба режима отключаем. если летели по директорам, то они просто исчезают, так как нет цели куда вести. если шли в автопилоте, то по идее переходим в CWS по обеим осям.

**Comment by ponemetski** [comment]
починил баг с тем когда не два автопилота

**Comment by soitanen** [comment]
заходил по глиссаде. перенстароил радиостанцию. ВОРЛОК выбило, а глиссада осталась....

**Comment by soitanen** [comment]
Ок. Только после выбивания остался заармированный FLARE

**Comment by ponemetski** [comment]
починил FLARE
