### ISSUE TITLE
CWS

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#34]
**всю индикацию** предлагаю описать в #35 если это будет удобно

режимы в нашей логике
- Cws - включается когда уже нажали соответствующую кнопку на MCP
- ~~RollActState.CwsTemp~~ (RollState == Off && ActiveAp.RollActState == Cmd) 
- ~~PitchActState.CwsTemp~~ (PitchState == Off && ActiveAp.PitchActState == Cmd) - если были в автопилоте (в CMD), то отключение режима или пересиливание по какой-то оси включит временно режим CWS по этой оси до момента, пока не активируется какой-то другой режим

работа когда не выбран режим:
- если летим в CMD и режим по крену или тангажу (или обоим) становиться Off (то есть он не выбран) то по этой (этим) оси попадаем в CWS
- при этом горят CMD и желтые CWS R и/или CWS P

работа когда пересилили:
- пересиливание по какой-то оси включит временно режим CWS по этой оси до момента, пока не активируется какой-то другой режим 
-  если перестать пересиливать то режим CWS останется опять же до активации нового режима

работа когда нажали кнопку на MCP:
- происходит переход  в ActState.Cws, 
- при этом ActState.Cmd отключается и 
- мы получаем режим FD (если директоры не включены будет пусто), 
- режимы по крену и тангажу без изменений
- при этом горят желтые надписи CWS R и CWS P
- на MCP лампы CMD не горят, горит лампа нажатого CWS
- автопилот помогает самолету лететь не по директорам а по заданному штурвалом режиму

физика полета, у нас есть заданные CWS режимом: targetRoll и targetPitch
по ним мы стандартным образом вычисляем rollCmd и pitchCmd

**Comment by soitanen** [comment]
стр. 334 и немного далее и стр. 364 и немного далее. Очень хорошо описано как работает CWS и по крену и по тангажу. Если вересиливаем по какой-то оси - то в той оси выбивается режим, который там был.

**Comment by soitanen** [comment]
нюанс режима APP и CWS. Если летим в автопилоте, пойман курсовой маяк и глиссадный, пересиливаем штурвал, то автопилот не перейдет в CWS по какой-то оси, а сразу весь отключится, директора останутся работать в режиме захода.

**Comment by ponemetski** [comment]
в CWS работает автотриммер?

**Comment by ponemetski** [comment]
- [ ] If the A/P was in the ALT HOLD or the ALT ACQ mode, the force on the control column must remain until the airplane is more than 250 feet from the MCP altitude. If not, the A/P will return to the ALT HOLD or ALT ACQ mode and stay in CMD.

**Comment by ponemetski** [comment]
пока не работает (не успел доделать)
- пересиливание (к тому же веб морда не умеет)
- сохранение крена и тангажа в момент активации CWS чтобы потом их выдерживать (ну либо уходить в нулевой крен если было меньше 6 градусов)

остальное можно пока проверять на предмет багов

**Comment by soitanen** [comment]
Извивни, сегодня времени совсем нет на проверку, только написать что-то могу.

Еще есть тема, что если в момент нажатия кнопки CMD не был выбран режим по крену и/или тангажу, то эта ось уходит в CWS.
И еще прикол. Стр. 298-299 того документа. Если при включении CMD мы плохо держим директора (границы как раз описаны в документы), то по той оси где плохо держим включается CWS

**Comment by ponemetski** [comment]
**Airplane Attitude Not Within F/D Limits**

The airplane roll attitude must be within 7 degrees of the F/D commands for VOR/LOC on course or selected bank angle limit of 10 degrees. The airplane roll attitude must be within 14 degrees of the F/D commands for all other modes. If the airplane roll attitude is not within these limits, the A/P goes into CWS roll and the F/D roll mode is reset.
The airplane pitch attitude must be within 3 degrees of the F/D commands for slaved G/S engage and MCP ALT ACQ mode. The airplane pitch attitude must be within 6 degrees of the F/D commands for all other pitch modes. If the airplane pitch pitch attitude is not within these limits, the A/P goes into CWS pitch and the F/D  mode is reset.

**Comment by soitanen** [comment]
потестил немножко.
Вроде адекватно. Ну то что после включения ЦВС он целится в тангаж 5 градусов - пока не сделано запоминание, это я понимаю. Сами переключения туда-сюда вроде ок.

**Comment by ponemetski** [comment]
> И еще прикол. Стр. 298-299 того документа. Если при включении CMD мы плохо держим директора (границы как раз описаны в документы), то по той оси где плохо держим включается CWS

сделал, пока закомментил потому что через веб морду бесполезно ловить директора, есть вопросы
1) у нас дергаются директора, надо их сгладить наверное
2) я ведь по идее могу лететь с отклонение от крена например 20 градусов, нажать CMD (попаду в CWS) и потом сразу ткнуть HDG SEL и включится CMD не смотря на то что у меня отклонение, верно?

**Comment by soitanen** [comment]
1. Ну да, мы про фильтр экспоненциальный обсуждали, который из FlightGear, адаптируется под deltaT.
2. Да, такое поведение правильно. В жизненной электронике просто будет разница - в первом случае директора тянут в сторону и элероны сразу бы дернулись туда. А во втором - все синхронизируется от текущего положения и движение пошло бы более плавно.

**Comment by ponemetski** [comment]
пока созрел такой план по пересиливанию
- пока мы в режиме цмд, проверяем постоянно расхождение между датчиком штурвала и командой мотору, если оно больше +/-10% в течении 0,5 сек то мы уходим в режим цвс по данной оси
- пока вы в цвс мы мотором едем к тому положению в котором человек держит штурвалы (тут надо придумать что то со скоростью, он может очень быстро приехать, а может и не надо)
- как только мотор догнал положение штурвала мы запоминаем крен или тангаж в котором самолет сейчас и начинаем его держать
- если в это время человек не отпускает: удержание крена и тангажа заданного в предыдущем действии предполагает что штурвал будет плавно уходить к нулевому положению (например мы повернули его на 25 градусов влево, чтобы держать крен 15, потребуется штурвал вернуть ближе к середине иначе крен будет больше и увеличиваться)
- так вот, если человек не отпускает: то мотор поведет штурвал от положения в котором держит его человек и когда отойдет достаточно, опять поедет к нему (вернемся в пункт 2)

**Comment by ponemetski** [comment]
в итоге 
- при пересиливании штурвала более чем 250 мс мы меняем целевые крен и тангаж для цвс
- при этом мотор уводим в 0
- при возвращении штурвала в 0 включаем мотор и пытаемся держать новые целевые

**Comment by ponemetski** [comment]
опять же предлагаю создавать отдельные ишьюсы на баги
