### ISSUE TITLE
CWS индикация

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#35]
Индикация CWS

- [x] PFD
- [x] mip (ASA) - тут пересекается с #42 я так понял что CWS вызывает оранжевое моргание (и его вызывает только он)

**Comment by soitanen** [comment]
да вроде ОК на ПФД. Мне, правда, почему-то кажется, что цвет AMBER должен быть чуть ярче и светлее, но могу ошибаться. Я у себя вот такой RGB делал 

(255, 191, 0)
--

**Comment by ponemetski** [comment]
по цвету добавил в список по ПФД
по оранжевой лампе А/П П РСТ на главной панели - сделал - проверил
