### ISSUE TITLE
деармирование автомата тяги на приземлении

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#36]
через 2 секунды после касания об землю (посадка самолета) тумблер АТ ARM должен автоматически упасть вниз. при этом красная моргающая лампа AT моргать не будет.

**Comment by soitanen** [comment]
в общем надо проверить на железе

**Comment by ponemetski** [comment]
отдельно механизм отключения тумблера я тестировал, проблем быть не должно.
надо будет пройтись по этой метке когда будет железо под рукой

**Comment by ponemetski** [comment]
поправил веб морду, чтобы можно было видеть отключение А/Т
