### ISSUE TITLE
активирование режима при появлении сигнала

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#37]
из-за особенностей х-плана возникает ситуация - летим вне зоны приема курсового маяка, он не ловится, тип радиостанции показывает 0. Но стрекла рисуется в центре, так передает х-плейн. когда вдруг влетаем в зону приема, то тип становится какой нужно, стрелка в центре, режим активируется. но потом стрелка очень быстро улетает из центра и получается фигня - мы имеем активированный режим, хотя по-хорошему активации не должно было быть. то же самое с глиссадной стрелкой возможно. надо сделать какую-то систему задержки, что после смены типа сигнала, как раз тогда пока стрелки бешено разлетаются из центра, не захватывать маяки. задержка 1-2 секунды я думаю должна быть.

**Comment by ponemetski** [comment]
добавил 2-ух секундную задержку, нужно обновить еще и GC

**Comment by soitanen** [comment]
вроде все ок
