### ISSUE TITLE
Автопилот отключится

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#42]
Автопилот отключится (любой и в любом режиме) 
- [x] если нажать кнопку отключения на штурвале
- [x] если опустить переключатель вниз
- [x] если нажать кнопку триммера на любом штурвале в любую сторону
- [x] на РУДе AUTOPILOT в положении CUTOFF - то отключится и не включится автопилот
- [x] второе нажатие на кнопку отключения на штурвале
- [x] при отключении автомата тяги (кроме как при посадке) А/Т моргает красным
- [x] двойное нажатие на отключение А/Т гасит красное моргание
- [x] желтое моргание лампы А/Т
- [x] экстренное отключение А/Р

1) какие особенности при двойном нажатии?
2) какие особенности при опускании переключателя на MCP?
3) при любом ли отключении автопилота моргает красная (желтая?) лампа A/T RST на галвной панели?

![unknown](https://user-images.githubusercontent.com/1931079/34014749-5e22f82a-e12d-11e7-8991-3f0560f3046d.jpeg)

**Comment by ponemetski** [comment]
![unknown](https://user-images.githubusercontent.com/1931079/34014749-5e22f82a-e12d-11e7-8991-3f0560f3046d.jpeg)

**Comment by soitanen** [comment]
1. Двойное нажатие кнопки на шутрвале имеется ввиду? Первое нажатие отключает автопилот, включает сирену и красную моргающую лампочку. Судя по видео, сирена и лампочка не могут быть отключены сразу, примерно полторы секунды второе нажатие не воспринимается. Если автопилот отключился по какой-то причине сам - то просто врубается сирена и красная моргающая лампочка. Т.е. кнопка используется как подтверждение того что ты понял, что автопилот отключился.
2. Обрубается оба автопилота. Пока он опущен - автопилот не включится.
3. Да, только не AT, а AP.

Еще момент - на РУДах справа внизу есть переключатели STAB TRIM. Если AUTOPILOT в положении CUTOFF - то отключится и не включится автопилот.
Еще автопилот отключится и не включится если пропадает давление в гидросистеме со стороны автопилота (A-A, B-B)

**Comment by ponemetski** [comment]
1) если при моргающей красной лампе А/Р включить автопилот то она перестанет моргать?
2) если пересиливать РУДы то будет моргать желтая лампа А/Т?
3) она (А/Т) еще когда-нибудь моргает?
4) красная лампа А/Т начинает моргать при любом отключении автомата тяги, верно?
5) при повторном нажатии на на отключение автомата тяги на РУДах красная лампа А/Т перестает моргать, верно?
6) если снова заармировать А/Т тумблером, то красная лампа погаснет?

**Comment by soitanen** [comment]
1. Да.
2. Не читал про такое, не могу вспомнить. Завтра в документации уточню.
3. Вроде нет.
4. Кроме автоматического отталкиваться через 2 секунды после посадки.
5. Да, по аналогии с автопилотом.
6. Точнее перестанет моргать.

18 дек. 2017 г. 10:07 ПП пользователь "ponemetski" <notifications@github.com>
написал:


   1. если при моргающей красной лампе А/Р включить автопилот то она
   перестанет моргать?
   2. если пересиливать РУДы то будет моргать желтая лампа А/Т?
   3. она (А/Т) еще когда-нибудь моргает?
   4. красная лампа А/Т начинает моргать при любом отключении автомата
   тяги, верно?
   5. при повторном нажатии на на отключение автомата тяги на РУДах красная
   лампа А/Т перестает моргать, верно?
   6. если снова заармировать А/Т тумблером, то красная лампа погаснет?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/ponemetski/extrinofms-issues/issues/42#issuecomment-352527157>,
or mute the thread

**Comment by ponemetski** [comment]
need_info - **желтое** моргание ламы А/Т
need_check - все остальное, проверил кроме случая когда через 2 сек после посадки А/Т отключается и при этом лампа не моргает

**Comment by soitanen** [comment]
flashing – indicates A/T airspeed error under following conditions:
• inflight
• flaps not up
• airspeed differs from commanded value by +10 or -5 knots and is not
approaching commanded value.

**Comment by soitanen** [comment]
Оно же в  другом документе
* True airspeed is valid
*True airspeed is 10 kts faster than target speed or true airspeed is less than target airspeed minus 5 kts
* Airplane is not accelerating to the target speed
* Flaps are greater than 0.5 degrees
* A/T MCP speed or A/T FMC speed is engaged for more than
5 seconds.

**Comment by soitanen** [comment]
по автопилоту там целая большая таблица, там много реальных отказов, которых у нас не будет.
Предлагаю сделать так:
* крен больше 45 - отключится
* угол атаки больше 16 - тоже отключится

**Comment by ponemetski** [comment]
по отключению А/Р сделал,

по желтой лампе А/Т чилал читал, понял что надо сделать так (ты поправь если не верно):
```
желттая А/Т соргает = (в воздухе) 
  И (закрылки > 0.5) 
  И (IAS +10/-5 от командной IAS) 
  И НЕ ( (Roll = Loc) И (Pitch = GS) ) // то есть не АРР режим
```

**Comment by soitanen** [comment]
+ И iasRate не в сторону сближения с заданной скоростью. Т.е. летели грубо 250, накрутили 150. Естественно что мы выпадаем из окна -5+10. Но если мы все же замедляемся, то моргать не будет. Учитывая глюки с нашим iasRate, возможно нужно брать какое-то отфильтрованное значение, типа иасРейт не в сторону по крайней мере 2 секунды из последних 3-х (типа как триммирование сделано)

**Comment by ponemetski** [comment]
все сделал, проверил

**Comment by ponemetski** [comment]
предлагаю баги писать отдельными топиками
