### ISSUE TITLE
Altitude deviation alert system

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#43]
Это система, которая гудит при подходе к высоте и гудит при отклонении от заданной высоты, попутно еще на PFD выводит некую символику (меняет толщину рамок, моргает).
Подробное описание в 22__034 стр. 248-251

**Comment by ponemetski** [comment]
![63df0fab-e5a4-40ac-b472-c733bccd2f68](https://user-images.githubusercontent.com/1931079/34073044-81d9831c-e2a2-11e7-8707-13dc7bbae848.jpeg)
![90313d8a-aacc-46a0-b604-28204f62e440](https://user-images.githubusercontent.com/1931079/34073049-97f3edfe-e2a2-11e7-9129-af6327d8a747.jpeg)
![65508d21-6371-4773-b9a3-adeccd563980](https://user-images.githubusercontent.com/1931079/34073055-a4ac9bc2-e2a2-11e7-90d2-2558d84cfd81.jpeg)

**Comment by ponemetski** [comment]
![30780c75-df09-4fa2-81ec-68ed2b8666c7](https://user-images.githubusercontent.com/1931079/34073112-cccf32ee-e2a3-11e7-8f74-4425ffae136d.jpeg)
![ebbada31-1feb-4ec0-a346-b60bb6b775b3](https://user-images.githubusercontent.com/1931079/34073122-ed742aa4-e2a3-11e7-86cc-fe13bfdd6f03.jpeg)

**Comment by soitanen** [comment]
Забыл написать. В документе фигурирует 300 футов как порог срабатывания системы отклонения, но сейчас все самолеты которые летаеют в RVSM пространстве вроде как переделали на 200 футов. Поэтому 300 футов меняем на 200.

**Comment by ponemetski** [comment]
**Звук** 
**377 AltitudeAlert.wav**
Здесь триггером выступает высота, выбранная на MCP в режимах APPROACHING или DEPARTURE. Сигнализация деактивируется, если закрылки в положении от 25 и выше, или если крафт захватил глиссаду.
Есть две разновидности: собственно, сигнализация о достижении выбранной высоты и сигнализация об отклонении от выбранной высоты.
Работает это так:
Сигнализации о достижении выбранной высоты
За 900 футов до достижении выбранной высоты, независимо от того, подходим мы к ней сверху или снизу, раздается звуковой сигнал. Играет разово, в момент прохода этой точки. Также появляется белая рамка вокруг заданной высоты, а рамка вокруг текущей высоты становится жирной. За 300 футов до выбранной высоты рамка вокруг выбранной высоты перестает отображаться.
2. Сигнализация об отклонении
Очевидно, что для того, чтоб появилось отклонение, нам сначала надо выйти на заданную высоту.
Сигнализация включается, если отклонение превысит 300 футов от заданной высоты, при этом рамка вокруг текущей высоты на PFD становится желтой и моргает. Здесь важно то, что звук проигрывается разово, при прохождении точки MCPalt плюс-минус 300 футов, а рамка остается желтой и продолжает моргать до тех пор, пока:
Отклонение не станет меньше 300 футов
Отклонение не станет больше 900 футов
Не будет задана новая высота на MCP.

**Comment by soitanen** [comment]
так и осталось 300 футов или мне показалось?

**Comment by ponemetski** [comment]
да, касяк, было 300, поменял на 200

**Comment by ponemetski** [comment]
> Моргание - должно быть с жёлтого на черный и обратно, у нас с жёлтого на белый. Толстая рамка с 200 до 900 футов должна быть, а внутри 200 футов должна быть тонкая как обычно.

готово

**Comment by soitanen** [comment]
почти правильно. моргание с желтого на черный - тоже должна быть толстая линия.

**Comment by soitanen** [comment]
теперь ок
