### ISSUE TITLE
Разармирование pitch G/S и FLARE

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#44]
> как поймать ошибку армирования. Летим в ЦВС по двум осям. лечу прямо по курсовому маяку, не в глиссаде. Нажимаю АПП. ворлок активен, глиссада армирована. я решаю развернуться, потому что все равно глиссаду не догоню уже. нажимаю HDG SEL - ворлок выходит в хединг селект, а вот глиссада не деармировалась.

- [x] получается, если ворлок активен, глиссада армирована и мы выходим из ворлока - надо разармировать глиссаду

- [x] еще нашел. был заармирован FLARE (посдака на двух автопилотах). стал уходить на второй круг - flare остался заармированным пока был режим ТОГА. отармировался только когда активировался ALT ACQ. Должен сразу по ТОГЕ разармироваться

**Comment by soitanen** [comment]
это ок
