### ISSUE TITLE
 Gload Normal/Axial/Side переводить в кабину

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#45]
В симуляторе значения для центра самолета, нам нужны еще значения для кабины.
Для #6 и не только.

>  Надо его ещё пересчитать из центра тяжести на кабину. 
Т.е. брать угловое ускорение вокруг вертикальной оси и расстояние от центра тяжести до кабины

**Comment by soitanen** [comment]
Gside_pilot = Gside + Rdot / 57.3 * 15 / 9.81
Rdot - это угловое ускорение вокруг вертикальной оси в радианах/сек/сек

**Comment by ponemetski** [comment]
rdot                 дельта между центром и кабиной
0.00375664  0.00010025
0.00366853  0.00009789
0.00371717  0.00009919
0.00361999  0.00009660
0.00388567  0.00010369
0.00410632  0.00010958
0.00396775  0.00010588
0.00390721  0.00010426
0.00395736  0.00010560
0.00402115  0.00010730
0.00416558  0.00011116
0.00432135  0.00011531
0.00412380  0.00011005
0.00440111  0.00011744
0.00439062  0.00011716
0.00412201  0.00010999
0.00225184  0.00006009
0.00876253  0.00023383
0.00431772  0.00011522
0.00426644  0.00011385
0.00510464  0.00013622
0.00495378  0.00013219
0.00714767  0.00019073
0.90968470  0.02427495
