### ISSUE TITLE
Индикация частоты/позывного, курса, расстояния до ILS

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#47]
я так понимаю что это две белые строки под A/T ARM?

<img width="345" alt="screen shot 2017-12-30 at 16 48 39" src="https://user-images.githubusercontent.com/1931079/34454678-51a46fd8-ed81-11e7-9837-c2f071fed5f9.png">

- откуда брать информацию которая туда пишется? какие там бывают надписи?

- [x] Индикация настроенной частоты/позывного - курса - расстояния до ИЛС

- [x] Сделать индикацию установленного курса радиостанции, убедиться, что она становится желтой и зачеркнутой, если долго не совпадает с другой стороной (точное время есть в FCOM -  Раздел номер 10 или 11, как раз про индикацию на приборах)

**Comment by soitanen** [comment]
Мы с тобой это делали для навигационного дисплея в режиме App, курс берём с
мср с соответствующей стороны

30 дек. 2017 г. 4:50 ПП пользователь "ponemetski" <notifications@github.com>
написал:

**Comment by ponemetski** [comment]
- If the tuned ILS frequencies disagree (for longer than one minute of time), the frequency turns amber with an amber horizontal line until set identically.
- If the approach courses entered in the MCP disagree (for longer than one minute of time), the course turns amber with an amber horizontal line through it.

**Comment by soitanen** [comment]
да, работает, понравилось

**Comment by soitanen** [comment]
Блин, не сразу понял. На PFD в левом углу ТОЛЬКО ILS (или отдельный localizer). А там сейчас и ВОР пролезает.

**Comment by ponemetski** [comment]
_видео есть в ТГ_

Я понял принцип так. Если мы настроили частоту илс (108.10 - 111.95, причем только нечетные окончания: 10, 15, 30, 35, 50, 55 и т.д.), то пишется слово илс, частота, курс, дистанция и появляются шкалы повторителей курса и глиссады снизу и справа. Если частота не подходит под илс - то исчезают все эти надписи.

Про нечетность не понял, вторая частота на видео 112.30, вроде четное окончание

Но она больше 111.95
Там не бывает илс

**Comment by ponemetski** [comment]
done
