### ISSUE TITLE
Вывод меток на ленту скорости

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#48]
- [x] Вывод flaps maneuvering speeds на ленту скорости
- [x] Метка ref
- [x] Белые метки ref+20 и v2+15
- [x] Вывод красных и желтых зон скоростей на ленте скорости, расчет ограничительных значений

<img width="39" alt="screen shot 2018-01-02 at 15 37 03" src="https://user-images.githubusercontent.com/1931079/34483971-d8d1e050-efd2-11e7-950a-d326208e9ca8.png">

<img width="133" alt="screen shot 2017-12-30 at 17 01 53" src="https://user-images.githubusercontent.com/1931079/34454759-3c7ed196-ed83-11e7-83ee-08595bf745f8.png">

**Comment by ponemetski** [comment]
тут есть 
1-40 - это понятно - скорость при закрылках

UP - скорость с поднятыми

Михаил, [Dec 30, 2017, 5:05:07 PM]:
Максимум 25 пишется. 30 или 40 не бывает

Alexander, [Dec 30, 2017, 5:05:21 PM]:
DN - ?

Михаил, [Dec 30, 2017, 5:05:27 PM]:
Тоже не бывает

Alexander, [Dec 30, 2017, 5:05:48 PM]:
v1 это скорость взлета при тоге?

Михаил, [Dec 30, 2017, 5:06:05 PM]:
Это скорость принятия решения

Вводится в cdu руками

Так же как и vr (rotate) и v2

Alexander, [Dec 30, 2017, 5:08:29 PM]:
ref - это как раз то самы Vref40?

Михаил, [Dec 30, 2017, 5:09:02 PM]:
Не обязательно 40

Это другая метка - выбранная через cdu для того положения закрылков на котором собираемся садиться (15, 30 или 40)

При этом в cdu есть возможность указать не текущую массу, а ту, которая будет на посадке, чтобы рассчитать скорость правильно

Alexander, [Dec 30, 2017, 5:10:50 PM]:
это в разделе DES?

Михаил, [Dec 30, 2017, 5:10:53 PM]:
А vref40 под текущую массу, чтобы считать скорости для закрылков считается всегда

Нет, approach

В верхний левый угол мы можем вставить свою массу желаемую для расчета

А в правой части 3 строчки как раз считают для 15 30 и 40 от той массы, что вставлена в левое Верхнее поле. Если ничего туда не вставляли, то считает от текущей

Причем текущей введённой до этого в cdu, а не взятой из симулятора

**Comment by ponemetski** [comment]
как получаются значения для желтых и красных зон скоростей?

**Comment by soitanen** [comment]
С верхней красной зоной довольно просто. Там показывается самое меньшее из расчетных нескольких значений. А именно - 340 узлов - это Vmo. Есть 0.82 Маха - это Mmo. Расчет сейчас покажу. Плюс если выпущены шасси - тогда 320 еще как лимит появляется. Если закрылки - то лимит по закрылкам лезет. Причем, насколько я понял из видео многочисленных, не пофактичсекому положению, а по положению ручки закрылков.
```
   <filter>
        <name>Mmo converted to IAS speed limit</name>
        <type>gain</type>
        <gain>1.0</gain>
        <update-interval-secs type="double">0.1</update-interval-secs>
        <input>
          <condition>
            <not-equals>
              <property>/instrumentation/airspeed-indicator/true-speed-kt</property>
              <value>0</value>
            </not-equals>
          </condition>
            <expression>
              <div>
                <product>
                  <property>/fdm/jsbsim/atmosphere/a-fps</property>
                  <value>0.82</value>
                  <value>0.5913174946</value>
                  <property>/instrumentation/airspeed-indicator/indicated-speed-kt</property>
                </product>
                <property>/instrumentation/airspeed-indicator/true-speed-kt</property>
               </div>
            </expression>
        </input>
        <input>
          <value>500</value>
        </input>
        <output>instrumentation/pfd/mmo-kt</output>
    </filter>
```


```
var mmoKt = getprop("instrumentation/pfd/mmo-kt") or 500;
		var maxIAS = 340;
		if ( mmoKt < 340 ) {
			var maxIAS = mmoKt;
		}
		if (flaps == 0.125) {
			maxIAS = getprop("limits/max-flap-extension-speed[0]/speed");
		} elsif (flaps == 0.250) {
			maxIAS = getprop("limits/max-flap-extension-speed[1]/speed");
		} elsif (flaps == 0.375) {
			maxIAS = getprop("limits/max-flap-extension-speed[2]/speed");
		} elsif (flaps == 0.500) {
			maxIAS = getprop("limits/max-flap-extension-speed[3]/speed");
		} elsif (flaps == 0.625) {
			maxIAS = getprop("limits/max-flap-extension-speed[4]/speed");
		} elsif (flaps == 0.750) {
			maxIAS = getprop("limits/max-flap-extension-speed[5]/speed");
		} elsif (flaps == 0.875) {
			maxIAS = getprop("limits/max-flap-extension-speed[6]/speed");
		} elsif (flaps == 1.000) {
			maxIAS = getprop("limits/max-flap-extension-speed[7]/speed");
		}
```

**Comment by soitanen** [comment]
Продолжаю.
В общем там где ХМЛ код - это перевод 0.82 маха в узлы. У тебя где-то подобный код есть.
Потом (у меня в коде нет) еще делаем переменную по шасси - если выпущены, то 320.
Ограничения по закрылкам - ФКОМ. 9-10-Trailing Edge Flaps

По верхней желтой зоне. Она появляется на большой высоте и скорости, пока я не понял как ее точно считать, можем временно без нее, потом добавим. Второй случай ее появления нужен. Это подсказка ограничения скорости по следующей позиции закрылков. Причем следующая не по позиции, а по алгоритму. алгоритм 1-5-15-30-40. Т.е. выпускаем на 1. желтой зоны нет, так как для 5 ограничение тоже 250. выпускаем на 5 - желтая зона будет до ограничения для 15. если выпустим на 10 - все равно для 15. Исчезает если мы на этапе захода стали вдруг убирать закрылки (уход на второй круг), если на страничке approach cdu выбрано положение закрылков для захода, на которое мы выпустили закрылки. Короче, если мы там забили 30, и выпустили на 30, то желтой зоны с ограничением для 40 не будет.

**Comment by soitanen** [comment]
Нижняя красная зона. Там скорость на которой начнет срабатывать стикшейкер. Данных толком нет. У меня вот такая табличка:
```
              <sum>
                <property>instrumentation/fmc/v-ref-40</property>
                <table>
                    <property>/fdm/jsbsim/fcs/flap-pos-norm</property>
                    <entry><ind>0</ind><dep>26</dep></entry>
                    <entry><ind>0.125</ind><dep>-6</dep></entry>
                    <entry><ind>0.375</ind><dep>-8</dep></entry>
                    <entry><ind>0.625</ind><dep>-22</dep></entry>
                    <entry><ind>0.875</ind><dep>-25</dep></entry>
                    <entry><ind>1</ind><dep>-26</dep></entry>
                </table>
              </sum>
```
table - это тут простая линейная интерполяция. А вот с vref40 еще веселее, ведь если перегрузка увеличивается, то выше вероятность свалится и этот красный забор будет приближаться. Поэтому надо, видимо, считать vref40 для массы умноженной на перегрузку (чисто для вывода этого значения).

НИжняя жетлая зона - хз как считать. Есть подозрение, что это тоже самое что расчет скорости сваливания по табличке выше, но vref40 расчитана с принудительной перегрузкой 1.3 относительно текщуей массы. т.е. когда пилот потянет на себя, то красная зона поползет вверх, а желтая - нет.

**Comment by ponemetski** [comment]
> Vref+20. Появляется при выборе Vref в CDU. Vref. Показывает выбранную в CDU Vref.

в cdu это где?
