### ISSUE TITLE
ND Airport and runway

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#53]
<img width="595" alt="screen shot 2018-01-14 at 13 21 52" src="https://user-images.githubusercontent.com/1931079/34914946-fea89724-f92d-11e7-9173-c9e87eb4e3a1.png">
<img width="858" alt="screen shot 2018-01-14 at 16 45 59" src="https://user-images.githubusercontent.com/1931079/34916508-76f03612-f94a-11e7-8b4e-d19a2c79bb95.png">

**Comment by soitanen** [comment]
Аналитика рисовании линии такова, что независимо от масштаба длина штриха остается неизменной в пикселях, но не в милях.
![image](https://user-images.githubusercontent.com/2819664/47270193-be444a00-d570-11e8-8014-079f90ae45f7.png)
![image](https://user-images.githubusercontent.com/2819664/47270199-c8664880-d570-11e8-8054-12d618a5f1bd.png)

**Comment by ponemetski** [comment]
готово, можно проверять

**Comment by ponemetski** [comment]
На счёт номера полосы, он на масштабе 20 и ниже?

Штрих я вроде по фоткам выбирал, надо белую покороче и пропуск покороче?

**Comment by soitanen** [comment]
ну фком пишет, что номер полосы при масшатабах (выбор на ефис) 5, 10, 20 или 40. Кстати, на крупных масштабах кружочек аэропорта со штрихом полосы не увидел.

**Comment by soitanen** [comment]
взял крупную картинку, загнал в Inkscape чтобы создать нужную линию. вот что получилось по ее параметрам (абсолют тут не важен, нужно подобрать пропорции по итогу)
ширина линии - 5.4 px
stroke-miterlimit:4; (это круголе окончание штриха, как я понял)
stroke-dasharray:12.6, 17.5; (длина белого штриха и пропуска. хз откуда длина - от центра закругления или нет, я просто поставил закругленные концы и подобрал параметры).

**Comment by ponemetski** [comment]
готово, можно проверять

**Comment by soitanen** [comment]
Ширина между краями рисуемой полосы - у нас широковато. Измерил на картинке относительно символа самолета - треугольника. У нас ширина между краями =34% от ширины нижней части треугольника. На фотке с прибора - 26%.
Второе сравнения - диаметр внутреннего круга (на котором отметка расстояния)
15/258 - наш экран, т.е. 5.81%
22/500 - прибор - 4.4%

Т.е. соотношения похожи, сейчас получается ширина 130% от необходимого размера.

**Comment by ponemetski** [comment]
уменьшил ширину

**Comment by soitanen** [comment]
ок

**Comment by ponemetski** [comment]
> убирать номер полосы, раз есть точка с эти же номером. Кроме того на этом скрине видно, что синий кружочек аэропорта прибытия все равно нарисован.

починил
