### ISSUE TITLE
рисование принимаемого ВОР маяка

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#54]
- [x] принимаю маяк. на карте рисуется пунктриная линия в зависимости от курса. Это ок. но сам значок маяка почему-то отсутсвует. пришлось нажимать кнопку STA чтобы увидеть его значок
- [x] перепутаны цифры. радиал - это линия от маяка к курсу. номер радиала и обозначает курс. сейчас получается наоброт - обозначен курс по этой линии К маяку.
- [x] был настроен на маяк (SPB, 113.4, Пулково). Был включен режим STA. Перенастроился на другую частоту - значок маяка полностью исчез и не появлялся, хотя должны были просто исчезнуть лучи и перекраситься в другой цвет.
- [x] mag var

**Comment by soitanen** [comment]
- [ ] был настроен на маяк (SPB, 113.4, Пулково). Был включен режим STA. Перенастроился на другую частоту - значок маяка полностью исчез и не появлялся, хотя должны были просто исчезнуть лучи и перекраситься в другой цвет.

**Comment by ponemetski** [comment]
поправил магнитное склонение для всех точек которые рисуются на карте
