### ISSUE TITLE
CDU - первый опыт использования

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#55]
Пишу пока просто все подряд, что бросилось в глаза
- [x] ROUTE. Ввёл аэропорт вылета. Хочу лететь туда же. Нажимаю на L1 - на scratchpad должен появиться его код - не берется.
- [x] ROUTE. Ввел полосу вылета. Хочу не поменять, а удалить. Нажимаю delete и пытаюсь вставить в runway - не стирается.
- [x] ROUTE. Послее ввода аэропорта вылета и прибытия, полосы вылета и (возможно) процедуры вылета SID в правой нижней строчке должно появиться ACTIVATE
- [x] PERF INIT - массы все в фунтах, надо перейти на килограммы, или оставть это как опцию в конфиге - фунты или кг (если вдруг в америке устанавливать).
- [x] центровка. сам самолет ее определять не умеет. мы ее должны вводить.
- N1 limit. Поменял температуру воздуха за бортом - обороты не пересчитались. Про уменьешние знаю что пока не работает, так как не давал тебе алгоритм. #59
- попытался удалить введные закрылки и V-speeds - не удаляются. Кнопка delete работает? #89

**Comment by ponemetski** [comment]
нужно ли везде делать функционал по удалению записей?

**Comment by soitanen** [comment]
Да, сегодня пару раз натыкался на это

26 февр. 2018 г. 22:59 пользователь "ponemetski" <notifications@github.com>
написал:
