### ISSUE TITLE
PFD localizer only indication

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#57]
Еще глюк поймал. Бывают заходы только по курсовому маяку. Его отклонения должно быть видно на ПФД. Я проверил - не получилось, при этом в режиме АПП на НД все показывает как надо. Как проверить. Берем аэропорт Тиват LYTV. Настраиваем частоту 111.30. Входим в локал мап, там видно как идет маяк, кидаем самолет в зону приема и проверяем.

**Comment by ponemetski** [comment]
можно проверить
если не будет работать то нужно прислать цифру
`DataNav1Type / DataNav2Type`
из консоли в золе приема только локалайзера
