### ISSUE TITLE
Впечатления от пробы на железе + какие-то забытые баги.

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#58]
Я тут напишу пока все подряд.
- [x] топливные насосы центрального бака. Когда они выключены тумблером, то лампа низкого давления не должна гореть.
- [x] все топливные насосы: когда включаем, то лампа низкого давления должна гаснуть не сразу, а с задержкой примерно 0.7-1.0 сек.
- [x] ADF - десятые доли так и не настраиваются.
- летим с включенными директорами, но с выключенным автопилотом. У меня срабатывал прикол, что режим скорости не активен, поэтому текущая скорость становилась заданной при активации например V/S или LVL CHG. Такого быть не должно. Видимо надо добавить проверку того, что тумблер автомата тяги в верхнем положении. #71
- [x] не работает автомат торможения
- [x] не выходят автоматически спойлеры на посадке.
- [x] максимальные обороты реверса слишком большие, должны быть не более 82%
- [x] очень нужен нижний экран с рулями #8 
- [x] на автопилоте не крутится колесо триммера, а должно
- опять же на автопилоте: есть подозрение, что сигнал отправляемый в моторы по положению не соответствует сигналу с датчика в это момент. Т.е. мне кажется что штурвал слишком на маленький угол поворачивается, по тангажу тоже по двигается. Может нужна таблица соответствия сигнала в мотор и сигнала с датчика?

**Comment by ponemetski** [comment]
> топливные насосы центрального бака. Когда они выключены тумблером, то лампа низкого давления не должна гореть.

то есть лампы центральных насосов не зависят от тумблеров?
очень желательно описать зависимости

**Comment by ponemetski** [comment]
> максимальные обороты реверса слишком большие, должны быть не более 82%

сколько сейчас максимум?
я отправляю в иксплейн command значение (егор я режу до 82%) но видимо раскручивается больше, то есть надо сильнее порезать

**Comment by ponemetski** [comment]
> опять же на автопилоте: есть подозрение, что сигнал отправляемый в моторы по положению не соответствует сигналу с датчика в это момент. Т.е. мне кажется что штурвал слишком на маленький угол поворачивается, по тангажу тоже по двигается. Может нужна таблица соответствия сигнала в мотор и сигнала с датчика?

там по идее у меня положение от -1 до +1 и у мотора точно такие же положения, я передаю мотору свои откалиброванные мин центр и макс и он уже ходит четко по ним - то есть надо откалибровать и ошибка между тем куда я хочу поставить штурвал и тем куда приведет его мторо будет +/-5%, не более

**Comment by soitanen** [comment]
Что-то я не смог понять, как цитировать тут с использованием планшета.... Так напишу.
Насосы: сейчас пишу только по центральные.
Тумблер выключен - лампа выключена.
Включаем тумблер - лампа горит короткий период времени и выключается (если есть топливо).
Лампа будет гореть при включённом тумблере если там топливо кончилось.
Теперь ещё элемент логики, но уже для все 6 топливных насосов. Я его просто сейчас вспомнил, не успел ещё у тебя его проверить, может сделано правильно. Насосы работают от сети переменного тока. Поэтому если у нас нет питания от переменного тока, то лампа будет гореть.
Реверс: сейчас вроде как по памяти было 92%.
По калибровке попробую посмотреть сегодня, запомню куда поворачивает штурвал автопилот, в морде увижу его сигнал, а потом выключу, проверку на такой же угол и сравню.

**Comment by soitanen** [comment]
Обновил.
Страница takeoff, GW/TOW - похоже что ошибочно добавляется вес торта сюда, сейчас у меня 51.4 zfw, 9.8 fuel, получается 61.2 gw. А тут пишет 73 тонны.
Второй момент - скорости v1 vr v2 он может предлагать до ввода центровки, они от нее не зависят

**Comment by ponemetski** [comment]
кроме первого сообщения закрыли

**Comment by soitanen** [comment]
просьба прогнать через фильтр все NDB, посмотреть какая у них бывает частота после запятой. 0, понятное дело, не интересен. А вот только 5 или что-то еще - интересно.
