### ISSUE TITLE
A/T, N1 limit - обороты при температуре

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#59]
разбираемся с оборотами при температуре и используем их в A/T (там по таблицам надо. мы выбираем тягу. 26килофунтов полная, либо 2 варианата дерейта - 24 или 22. берем ФКОМ стр 383, 398 и 413)

**Comment by soitanen** [comment]
добавлю к информации выше.
Берем ту температуру, что ввели в CDU (насколько я помню, сейчас у нас костыль, который берет реальную температуру при нажатии кнопки ТОГА). Когда ввели температуру, то появляются циферки N1 Limit, рассчитанного по табличке. Если выбираем дерейт - то они, естественно, меняются. Если делаем уменьшение по температуре - тоже меняются. Алгоритм сейчас распишу.
Стр. 384, таблица 1. Мы вводим assumed temp/real temp (OAT). Значение высоты аэродрома вылета берем из CDU по данным аэродрома вылета, по идее в базе должно это быть. Если assumed temp получается больше, чем по этой проверочной таблице, то по идее данные взять не должно и должно выдать в ответ INVALID ENTRY.
По таблице 2 определяем максимальные обороты, но это еще не финал.
По таблице 3 определяем еще дополнительное уменьшение оборотов и из оборотов по таблице 2 вычитаем часть оборотов по таблице 3. В принципе под таблицей 3 как раз написана последовательность действий.

И методы эти можно как по одиночке использовать (только дерейт или только температурный метод), так и вместе - и дерейт, и температуру.

**Comment by ponemetski** [comment]
#10

**Comment by ponemetski** [comment]
можно проверять

сделал:
- сам расчёт, 
- проверку корректности мнимой температуры, 
- отображение на upperd и 
- теперь этот лимит берется при нажатии toga при взлете

проблема с тем что этот лимит может быть не указан и тогда режим toga будет пытаться привести обороты к 0, видимо надо отщелкивать тумблер автомата тяги если обороты не рассчитаны

**Comment by soitanen** [comment]
ну, кстати, в жизни именно так и есть. Не вставил температру, армируешь
автомат тяги - тумблер обратно падает. В воздухе уже пофиг - он берет
данные от датчиков температры. Можно так сделать, будет реалистично, но
нужно сделать чтобы тумблер падал не сразу, а через секунду, например.
Иначе его точно сломают, потому что будут пересиливать. А так вроде и
поднял, но упал через секунду.

ср, 17 окт. 2018 г. в 1:13, ponemetski <notifications@github.com>:

**Comment by ponemetski** [comment]
сделал
- надпись RED если указана мнимая температура (работает и на второй старинце тэйкофа)
- если не задали лимит по оборотам но заармировали a/t и нажали toga то будут автоматом посчитаны обороты для текущей высоты и температуры

**Comment by soitanen** [comment]
вроде все как надо
