### ISSUE TITLE
Список доработок по PFD

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#6]
- [x] На ленте высоты не должно быть лидирующих нулей в цифрах
- [x] Округление радиовысотомера:
  - от 500 футов до 2500 - по 20
  - от 100 футов до 500 - по 10
  - ниже 100 футов - по 2
.
- [x] На земле радиовысотомер показывает должен показывать -4
- [x] Сравнить размеры цифр заданных значений скорости и высоты
- [x] Уточнить и проверить размеры цифр на компасе снизу
- [x] Скорость изменения давления на высотомерах
- [x] В компасе внизу заданный курс должен всегда состоять из трех цифр
- [x] В компасе периодически пропадает из вида линия Track
- [x] В компасе задатчик курса уходит не туда из-за неправильного приведения 180-360 градусов
- [x] Оживить индикатор скольжения (0.1G бокового ускорения приводит к сдвигу на максимум, т.е. на одну ширину прямоугольника). slipSkid = бокове ускорение в g
`

		if (slipSkid > 0.1) slipSkid = 0.1;
		if (slipSkid < -0.1) slipSkid = -0.1;
		me["slipSkid"].setTranslation(slipSkid*-460,0);
		me["bankPointer"].setRotation(-roll*D2R);

		if (math.abs(roll) < 35) {
			me["bankPointerTriangle"].setColor(1,1,1);
			me["bankPointerTriangle"].setColorFill(0,0.477,0.725,1);
			if (math.abs(slipSkid) == 0.1) {
				me["slipSkid"].setColor(1,1,1);
				me["slipSkid"].setColorFill(1,1,1);
			} else {
				me["slipSkid"].setColor(1,1,1);
				me["slipSkid"].setColorFill(0,0.477,0.725,1);
			}
			
		} else {
			me["bankPointerTriangle"].setColor(1,0.749,0);
			me["bankPointerTriangle"].setColorFill(1,0.749,0,1);
			if (math.abs(slipSkid) == 0.1) {
				me["slipSkid"].setColor(1,0.749,0);
				me["slipSkid"].setColorFill(1,0.749,0);
			} else {
				me["slipSkid"].setColor(1,0.749,0);
				me["slipSkid"].setColorFill(0,0.477,0.725,1);
			}
		}`
- [x] Сделать цветовую сигнализацию превышения крена
- [x] Сделать на FMA появление зеленых рамок и их пропадание через 10 секунд
- [x] Оживить директора, проверить, что есть фильтр, добавляющий плавность (экспоненциальный фильтр желателен)
- [x] Добавить индикацию Ground Speed ниже ленты скорости. Она автоматически переключается в индикацию числа Маха, если М > 0.4, обратное переключение при М < 0.38
- [x] Оживить повторители глиссады и курсового маяка. Глиссадный выводится только в передней полусфере выставленного значения COURSE на MCP
- [x] Разобраться с индикацией по LOC - expanded не expnaded
- Индикация настроенной частоты/позывного - курса - расстояния до ИЛС #47
- Сделать индикацию установленного курса радиостанции, убедиться, что она становится желтой и зачеркнутой, если долго не совпадает с другой стороной (точное время есть в FCOM)  #47
- Вывод flaps maneuvering speeds на ленту скорости #48
- Вывод красных и желтых зон скоростей на ленте скорости, расчет ограничительных значений #48
- [x] цвет AMBER (255, 191, 0) из #35 
- [x] центральный белый квадрат символа самолета на FPD должен быть поверх директоров. Весь остальной символ самолета - под директорами. фон внутри этого центрального квадрата - черный.
![image](https://user-images.githubusercontent.com/2819664/33221714-bbcfc5f0-d162-11e7-8df7-a0d657b7dca1.png)
![image](https://user-images.githubusercontent.com/2819664/33221729-d969d722-d162-11e7-86a1-94b6a10712fa.png)

**Comment by ponemetski** [comment]
- [ ] Position trend vector code in Nasal (есть алгоритм в письме)

**Comment by soitanen** [comment]
На ленте высоты не должно быть лидирующих нулей в цифрах

**Comment by soitanen** [comment]
Округление радиовысотомера:
- от 500 футов до 2500 - по 20
- от 100 футов до 500 - по 10
- ниже 100 футов - по 2

На земле радиовысотомер показывает должен показывать -4.

**Comment by soitanen** [comment]
Сравнить размеры цифр заданных значений скорости и высоты
Уточнить и проверить размеры цифр на компасе снизу

**Comment by ponemetski** [comment]
> Оживить индикатор скольжения (0.1G бокового ускорения приводит к сдвигу на максимум, т.е. на одну ширину прямоугольника). slipSkid = бокове ускорение в g

нужно проверить в ту ли сторону двигается прямоугольник

**Comment by ponemetski** [comment]
кроме

- Индикация настроенной частоты/позывного - курса - расстояния до ИЛС #47
- Сделать индикацию установленного курса радиостанции, убедиться, что она становится желтой и зачеркнутой, если долго не совпадает с другой стороной (точное время есть в FCOM) #47

- Вывод flaps maneuvering speeds на ленту скорости #48
- Вывод красных и желтых зон скоростей на ленте скорости, расчет ограничительных значений #48

для которых отдельные issue

**Comment by soitanen** [comment]
- прямоугольник скольжения оказался движущимся не в ту сторону

**Comment by ponemetski** [comment]
поменял знак
