### ISSUE TITLE
без директоров (тумблеры выключены) на земле кнопка тога не активирует логику взлета

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#60]

**Comment by soitanen** [comment]
Это похоже я тогда натупил, ниже 80 узлов на земле и не должно ничего происходить... после 80 надо проверить - завтра попрошу на железном кокпите это сделать.

**Comment by ponemetski** [comment]
https://bitbucket.org/ponemetski/extrinofms/commits/98e8f69b4f00980bb40540287c278b72d658415b

**Comment by soitanen** [comment]
проверил дома. ВЫключены директора. дал тягу, разогнался выше 80 узлов - режим по тангажу стал ТОГА, но директора не повились.
в fcom написано что  pitch mode to/ga активируется если нажать кнопку после 80kn и до 2000agl или150 сек после отрыва. Значит если режим установить вручную при выкл. FD и нажать to/ga директорных стрелок не будет.
а если после - то появятся, но при переходе по тангажу из режима TOGA в какой-либо другой, например ALT ACQ - опять исчезнут, если мы так и не включим тумблеры директоров

**Comment by ponemetski** [comment]
[17:51, 8/22/2018] Alex: получается могут тогу нажать до 80 и после и в зависимости от этого надо показывать директора? не очень понятны все возможные случаи
[18:24, 8/22/2018] Михаил: Вот как раз до 80 ничего вроде не должно быть...

**Comment by ponemetski** [comment]
получается нужно добавить:
если (директора выключены и скорость > 80 и (радивысота < 2000 или секунд после отрыва < 150) и нажали тогу) то активировать тогу и покзать директорные стрелки независимо от тумблеров

**Comment by soitanen** [comment]
после установки нового софта в афимолле стали вылезать еще каие-то приколы, с которыми раньше вроде не сталкивались (сказывается привычка к мадженте у пилотов), ну так я в итоге спросил пилота, что будет если у нас на земле на месте заармирован автомат тяги, директора выключены, а мы нажимаем ТОГУ. Он ответил без запинок, потому что говорит, что бывало и не раз, что взлетали забыв включить директора, или специально без них. В общем по нажатию ТОГИ тяга переходит в режим N1, причем именно взлетный, РУДы уходят вперед, а вот по крену и тангажу все пусто будет, директора не появляются. И дальше автомат тяги уйдет в THR HLD, затем в АРМ, затем, если установлена опция, автоматически уменьшит тягу на thrust reduction altitude. Сейчас у нас еще и ТОГА загорается, и переходит в ALT ACQ, что, получается, ошибка.

**Comment by ponemetski** [comment]
добавил виртуальный режим A/T = TO такой же как GA 
по максимуму постарался минимизировать эффект от изменений 
но все равно нужно протестить потому что зависимостей в коде автопилота много

**Comment by soitanen** [comment]
С мест претнзий не было, причем я проверил, что у всех обновилось, считаю, что надо закрыть.
