### ISSUE TITLE
MCP окошко скорости должно гаснуть (проблема на железе, найти нужный бит)

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#62]
помимо того что нужно уметь рисовать точку букву А и 8 перед числом, нужно уметь полностью гасить экран 

<img width="312" alt="screen shot 2018-07-14 at 00 14 13" src="https://user-images.githubusercontent.com/1931079/42714179-e5127496-86fa-11e8-8952-1a6f2ad271bb.png">

**Comment by soitanen** [comment]
гасится
