### ISSUE TITLE
Глюк автомата торможения

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#64]
- [x] Взлетаем, ставим автомат торможения в РТО, в полете не переводим его в офф, садимся - самолёт тормозит в полную силу. РТО должен сразу деармироваться при отрыве от полосы.

- [x] При посадке если при первом касании была тяга, то автомат торможения сразу отключается. Всё-таки он должен начать тормозить когда мы уберем тягу, а у тебя получается (как мне кажется по работе системы), что при касании один раз идёт проверка условий срабатывания, тяга не согласуется и все, отключается автомат. Это неправильно

- [x] Разобраться с RTO когда сполеы в down он толи не включается толи выключается

**Comment by ponemetski** [comment]
по второму пункту - по коду не вижу такого "при касании один раз идёт проверка условий срабатывания, тяга не согласуется и все, отключается автомат"

но, вижу историю со сполерами: если спойлер стоит в нуле (то есть DOWN) то автомат после касания будет деармирован пересиливанием (как если бы нажали педали тормозов)

**Comment by ponemetski** [comment]
из whatsapp

если арм это чуть больше 0, то при посадке на газу может сработать автомтическое убирание спойлеров в 0

если руды на 15% своего хода выдвинуты, то мотору будет дана команда увести рычаг спойлеров в down
как только он туда приедет, автомат торможения деармируется

**Comment by soitanen** [comment]
Какая у нас логика запрыгивания спойлеров обратно? Может там только при большом газе надо им запрыгивать? Тогда не будет нашего глюка автомата торможения номер 2

**Comment by ponemetski** [comment]
> надо сделать логику не спойлерс > 0, а > 0.5

готово, можно проверять

**Comment by ponemetski** [comment]
> надо сделать логику не спойлерс > 0, а > 0.5

готово, можно проверять

**Comment by soitanen** [comment]
по спойлерам мне понравилось, хорошо, а вот то что автомат не начинал работу - вроде как связано с газом. Я сел полностью в автомате и пока руками не додвинул руды до упора вниз - не работало автоматическое торможение. По какому положению у нас начинает работать?

**Comment by soitanen** [comment]
не считаю на данный момент глюком.
