### ISSUE TITLE
Список доработок по ND

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#7]
- Position trend vector code in Nasal (есть алгоритм в письме) #51 
- [x] В режиме MAP если мы настроены на частоты ILS, а на EFIS выбраны VOR маяки, то мы должны видеть надпись VOR 1 & VOR 2, частоты не будет, позывного не будет (тире), дистанции не будет, зеленых стрелок, показывающих на маяк, тоже не будет. Вообще в этих двух нижних углах может быть только надпись VOR или ADF, в зависимости от выбранного на EFIS. ILS там не отображается никогда.
- [x] сделать отображение стрелок на радиомаяки, отображение частоты и позывного
- [x] сделать отображение аэропортов и прочих навигационных штук на карте #50 
- сделать рисование выбранной полосы для захода и продолженной на 15 миль ВПП в обе стороны #53 
- зеленая арка двигающаяся #52 
- [x] завести группы и добавлять динамические элементы в группы для того чтобы лекго управлять очередностью их слоев

**Comment by soitanen** [comment]
- [ ] Position trend vector code in Nasal (есть алгоритм в письме)

**Comment by soitanen** [comment]
Хорший крупный снимок, где видна очередность слоев на ND
![image](https://user-images.githubusercontent.com/2819664/33482184-e09bcbcc-d6a8-11e7-8b43-f2ed7956e3ad.png)
