### ISSUE TITLE
Нуль-зона по педалям руля направления

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#70]
Добавить в конфиг параметр rudder_nullzone или как-то иначе его обозвать, его смысл - уменьшить нежелательное отклонение самолета из-за несовершенства конструкции педалей. если ставим параметр, например, 50, до когда дачтик дойдет до отклонения в 50 от нейтрали, то только тогда пойдет нарастание сигнала, причем именно от 0, а не скачком на 50.

**Comment by ponemetski** [comment]
# hw wtf
# rudder zero zeone (percents)
hwtf.rudder.zerozone = 3

**Comment by soitanen** [comment]
думаю, что все ок
