### ISSUE TITLE
Проблема с точкой LAZ

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#74]
<img width="1119" alt="screen shot 2018-03-19 at 23 32 53" src="https://user-images.githubusercontent.com/1931079/37620641-e1031c08-2bcd-11e8-9fb8-c35a6cf2ab05.png">
глюк на НД в режиме МАП с  включенным СТА
Лазаревское в районе Сочи
LAZ

**Comment by soitanen** [comment]
![whatsapp image 2018-09-15 at 19 15 55](https://user-images.githubusercontent.com/2819664/45939710-4caec580-bfdd-11e8-88ae-7fb258c4b35d.jpeg)
Аналогичная фигня где-то под Москвой.

**Comment by soitanen** [comment]
ок
