### ISSUE TITLE
ApRoll -> cmd по таблице от скорости

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#75]
```
ApRoll -> cmd
targetRollRate = (targetRoll - currentRoll) * ApRollModeSns
```

расчет targetRoll - он где-то захардкоден? Там особенность вылезла. На маленьких скоростях самолет слишком быстро меняет курс и начинать выводить самолет из крена нужо намного раньше (по градусу недоворота н азаданный курс), чем при полете на большой скорости. Нужно вынести этот параметр в кофиг и сделать возможным его изменение как в случае с тангажом зависимым от скорости. Скорее всего у нас targetRoll=deltaHeading * coeff.

**Comment by ponemetski** [comment]
было
```
double targetRoll = Range(delta * 1.5, -bankLimit, bankLimit);
```

**Comment by ponemetski** [comment]
добавил

```
# targetRoll = Range(delta * ApRollDeltaK, -bankLimit, bankLimit)
# formatA can be a single value, example: 0.1
# formatB ias1: p1, ias2: p2, ias3: p3, example: 140: 0.7, 280: 0.3, 340: 0.05
system.config.ApRollDeltaK = 1.5
```

**Comment by soitanen** [comment]
надо в конфиг дефолт поставить
system.config.ApRollDeltaK = 140: 0.75, 170: 0.87, 220: 1.5, 250: 1.85, 320: 2.3

**Comment by ponemetski** [comment]
готово.
можно закрывать если все остальное ок

**Comment by soitanen** [comment]
Да, остальное хорошо.
