### ISSUE TITLE
ND проблема с точкой 

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#76]
Геленджик
<img width="354" alt="screen shot 2018-03-19 at 23 38 34" src="https://user-images.githubusercontent.com/1931079/37620940-ae725cd0-2bce-11e8-8fd2-b1bc5f4e244e.png">
<img width="370" alt="screen shot 2018-03-19 at 23 38 59" src="https://user-images.githubusercontent.com/1931079/37620955-b676468a-2bce-11e8-8b58-d29ec1540c64.png">

**Comment by soitanen** [comment]
ок
