### ISSUE TITLE
Запуск двигателя

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#77]
![2018-03-19 23 42 23](https://user-images.githubusercontent.com/1931079/37621165-30f54410-2bcf-11e8-8d52-fb61d99224c4.jpg)

![2018-03-19 23 42 26](https://user-images.githubusercontent.com/1931079/37621169-32353fc4-2bcf-11e8-8b53-ea454f540126.jpg)

По первому скрину. По положению engine start switch. У тебя сейчас написано, что если не off, то слать 4 в симулятор. Это не верно.
Правильная логика:
StartEngXSel = 0   -> Starter = 0
StartEngXSel = 2   -> Starter = 3
StartEngXSel = 3   -> Starter = 4
StartEngXSel = 1   -> смотрим на переключатель L-both-R между engine start switches. Если он L - посылаем в стартер 1, если R - 2, если both - 3

разаобрался с глушением и запуском самолета. В настройках самого самолета стояло, что стартер автоматически подает топливо. Из-за этого и происходил рост EGT раньше времени, и не глушился самолет если engine start switch стоял в CONT. Исправил в самом самолете. Осталось только прикол именно со стартером переписать, тогда вообще все ок должно быть.

правда, надо потом туда будет добавлять логику анализа давления воздуха в патрубках, чтобы процесс запуска не начинался, если давления воздуха нет.

прикол со стартером. У Х-Плейна странно работает стартер, ты отсылаешь ему 4, а он сам меняет ее обратно на 3. Но если часто отсылать - то все нормально запускается. Настроил дома правильное время раскрутки оборотов. Отправил файлы в Краснодар, но там получается полная фигня... Стартер раскручивается гораздо медленнее. Это может быть из-за того, что там сигнал летает по сети и Х-Плейн успевает сбрасывать его с 4 до 3 (т.е. выключает сам стартер) чаще?

что-то пока датареф не нашел. нашел такую фишку, что можно повесить на кнопку джойстика имитацию кнопки стартера. пока держишь - он равен 4. отпускаешь - прыгает в 3

ты умешь отправлять команды? имеется ввиду програма твоя

в луа есть, например, такая фишка - command_once("sim/operation/regen_weather")

еще вот такую конструкцию на форуме увидел - XPLMCommandButtonPress(xplm_joy_start_0); 
   else
      XPLMCommandButtonRelease(xplm_joy_start_0);

 надо будет усложнить код стартера. Чтобы на всех тренаежерах независимо от сети и прочих штук работало одинаково. Сейчас пришлю сюда точное наименование команды стартера

sim/starters/engage_starter_1 и соответственно такой же 2

**Comment by soitanen** [comment]
Еще заметил, что на Upper EICAS не хватает в процессе запуска надписи START VALVE OPEN (по идее горит когда engine start switch находится в GRD).
Также ниже этих двух надписей еще есть лампа LOW OIL PRESSURE. Тоже должна гореть пока двигатели не запущены.

**Comment by ponemetski** [comment]
> Х-Плейн успевает сбрасывать его с 4 до 3 (т.е. выключает сам стартер)

нашел как сделать чтобы 3 и 4 не менялись местами 


1) как вот это нужно поставить?

<img width="386" alt="screen shot 2018-08-23 at 23 26 43" src="https://user-images.githubusercontent.com/1931079/44550142-050df300-a72c-11e8-9436-b6394725285c.png">

2) не совсем ясно вот это:

> StartEngXSel = 1 -> смотрим на переключатель L-both-R между engine start switches. Если он L - посылаем в стартер 1, если R - 2, если both - 3

2.1) если переключатель двигателя находится в CONT то это единственный случай когда мы смотрим на тумблер L-both-R, верно?

2.2) если у обоих двигателей стоит CONT а переключатель L-both-R стоит в L то в левый мы шлем 1 а в правый тоже 1?

2.3) верно ли что и правым зажигателем и левым зажигателем можно поджечь топливо в любом из двигателей?

**Comment by ponemetski** [comment]
в общем нужно знать какие настройки самолета, а то сейчас он и топливо сам подает если стартер и как-будто стартер сам включает если топливо подать в полете

**Comment by ponemetski** [comment]
Нужно добавить в enhancement.lua 

в конце объявления датарефов (line ~255):
```
DataRef("eng1_ignition", "sim/cockpit2/engine/actuators/ignition_on", "readonly", 0)
DataRef("eng2_ignition", "sim/cockpit2/engine/actuators/ignition_on", "readonly", 1)
```
внутри функции update() которая выполняется в цикле (line ~1511):
```
-- extrino fms starter fix
if eng1_ignition == 4 then
	command_once("sim/starters/engage_starter_1")
end
if eng2_ignition == 4 then
	command_once("sim/starters/engage_starter_2")
end
```

Это позволяет избавиться от проблемы:
> Х-Плейн успевает сбрасывать его с 4 до 3 (т.е. выключает сам стартер)

**Comment by soitanen** [comment]
Работает!
