### ISSUE TITLE
ATC transponder

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#79]
прописать логику работы ответчика, он же transponder. Все 4 цифры от 0 до 7. Должны отправляться в X-Plane.

**нужна галка в которую собственно писать**

**Comment by soitanen** [comment]
104-1 - код транспондера.
104-0 - режим работы:
  0 - off
  1 - standby
  2 - xpndr
  3 - ta/ra
  4 - test

**Comment by ponemetski** [comment]
код трансподнера отправляем, все цифры от 0 до 7.
режим работы - буду на железе искать, потому что софт пока не умеет получать состояние переключателя режима

**Comment by soitanen** [comment]
Ох... немного не понял самого вопроса - какое каим - что именно (положение ручки) чему? Цифры - это биты в поллах, как я понимаю? По факту нам отправлять в симулятор не надо это. Там просто при некоторых положениях на ND есть надпись TA ONLY (может еще какая бывает)

**Comment by soitanen** [comment]
test - test
stby - standby
alt off - xpndr
alt on - xpndr
ta - ta/ra
ta/ra - ta/ra

**Comment by soitanen** [comment]
работает
