### ISSUE TITLE
Список задач по Lower EICAS

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#8]
- [x] Сделать отображение рулей
- [x] Добавить к нему отображение давления в тормозах
- [x] Выключать по повторному нажатию
- [x] Зажигать экран если что то красное (потом не зажигать пока не наладилось и снова не покраснело)
- [x] В состоянии покоя показывать положение руля высоты напротив центральных рисок

**Comment by ponemetski** [comment]
фото того как должно выглядеть есть в почте

**Comment by soitanen** [comment]
![image](https://user-images.githubusercontent.com/2819664/32844397-5b334220-ca33-11e7-941a-e64934922d54.png)

**Comment by ponemetski** [comment]
по дебагу в итоге: 
1) предлагаю делать амбер цветом
2) добавляю 4 цифры для тормозов внутри овалов-колес 
3) положения с датчиков амбером
4) положения моторов красным
5) активация из cdu

**Comment by ponemetski** [comment]
Дебаг нужно оформить отдельным ишью

**Comment by ponemetski** [comment]
> В состоянии покоя показывать положение руля высоты напротив центральных рисок

готово

**Comment by ponemetski** [comment]
> Зажигать экран если что то красное

при каком значении N2 становится красным на MFD? сейчас > 105
еще у нас там умеет быть красным от температуры масла > 155 и давления масла < 13

**Comment by ponemetski** [comment]
> Зажигать экран если что то красное

при каком значении N2 становится красным на MFD? сейчас > 105
еще у нас там умеет быть красным от температуры масла > 155 и давления масла < 13

**Comment by soitanen** [comment]
Я имел ввиду автоматическое выпрыгивание нижнего экрана двигателей при откзах двигателя, как в ФКОМ написано:
Secondary engine indications are displayed:
• when CDS initially receives power
• when selected by the Multi-Function Display (MFD)
• in flight when an engine start lever moved to CUTOFF
• in flight when an engine fails
• when a secondary engine parameter exceeds normal operating range.

**Comment by ponemetski** [comment]
> Я имел ввиду автоматическое выпрыгивание нижнего экрана двигателей при откзах двигателя, как в ФКОМ написано:
> Secondary engine indications are displayed:
> • when CDS initially receives power
> • when selected by the Multi-Function Display (MFD)
> • in flight when an engine start lever moved to CUTOFF
> • in flight when an engine fails
> • when a secondary engine parameter exceeds normal operating range.

 готово, можно проверять

**Comment by ponemetski** [comment]
Да, я та понял нужно просто чуть затормаживать перемещение, нужны
какие-нибудь цифры рэйта

**Comment by soitanen** [comment]
так ведь мы же где-то реальную цифру программиовали, что-то в районе 50 градусов в секунду

**Comment by ponemetski** [comment]
готово

**Comment by soitanen** [comment]
вроде все ок
