### ISSUE TITLE
Rising runway symbol

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#81]
Реализовать зеленую ВПП на PFD. Правильная логика есть у меня в pfd.nas

**Comment by ponemetski** [comment]
сделал по примеру из pfd.nas
вопрос такой, при отклонении 0.3 точки у нас полоса должна так сильно уходить вправо? гораздо сильнее ромбика локалайзера

<img width="1079" alt="screen shot 2018-10-25 at 01 42 10" src="https://user-images.githubusercontent.com/1931079/47465823-39b72d00-d7f7-11e8-8da4-11a0756d51c0.png">

**Comment by ponemetski** [comment]
поправил по новой

**Comment by soitanen** [comment]
вроде сейчас все ок
