### ISSUE TITLE
Разобраться с созданием точки по методу точка-радиал-удаление

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#88]

**Comment by soitanen** [comment]
по моим сегодняшним экспериментам все работало, видимо до этого было связано с глюком ЛНАВ. Если что - создам заново с конкретными примерами.

**Comment by ponemetski** [comment]
<img width="296" alt="screen shot 2018-10-17 at 19 40 06" src="https://user-images.githubusercontent.com/1931079/47102096-7bb70080-d244-11e8-9dc6-078ccefca405.png">

**Comment by ponemetski** [comment]
поправил названия у создаваемых точек, но нашел проблемы сточками у которых не указан радиал типа GENPA/-5, буду разбираться

**Comment by ponemetski** [comment]
еще сделал чтобы не рисовалась линия если точки в cdu не соединены

**Comment by soitanen** [comment]
ок
