### ISSUE TITLE
CDU везде сделать функционал по удалению записей

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#89]
"попытался удалить введные закрылки и V-speeds"

**Comment by ponemetski** [comment]
- [ ] Approach
- [ ] Arrivals
- [ ] DepArrIndex
- [ ] Departures
- [ ] Ident
- [ ] InitRefIndex
- [ ] Legs
- [ ] Menu
- [ ] N1LimitPreflight
- [ ] PerfInit
- [ ] PerfLimits
- [ ] PosInit1
- [ ] PosInit2
- [ ] PosInit3
- [ ] Route1
- [ ] RouteX
- [ ] TakeoffRef1
- [ ] TakeoffRef2

**Comment by ponemetski** [comment]
можно проверять

**Comment by soitanen** [comment]
ок
