### ISSUE TITLE
высота принятия решения

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#90]
Нет возможности менять minimums на pfd через EFIS.
от пилота: можно выставлять разные минимумы слева и справа, звуковая система скажет минимумс по значению той стороны, где активен МАСТЕР (короче где пилотирующий).

**Comment by ponemetski** [comment]
отображение RADIO/BARO работает, не знаю откуда информация, но нужно нажимать RST чтобы эти они появились, сначала в амбер потом в зеленом цвете 

<img width="601" alt="screen shot 2018-10-02 at 23 02 07" src="https://user-images.githubusercontent.com/1931079/46373641-3537a280-c697-11e8-974f-81e189b49228.png">

**Comment by ponemetski** [comment]
сделал:
1) по умолчанию отображение RADIO/BARO зеленым цветом
2) звуки SoundMinimums SoundPlusHundred SoundApproachingMins теперь зависят от стороны на которой мастер

**Comment by ponemetski** [comment]
Нашел вот такую аналитику от Камиля (видимо забыл её реализовать полностью):

Если BARO, то
- Отображается под авиагоризонтом, значение в футах от уровня моря
- Становится желтым и моргает 3 сек, если судно снижается ниже заданного уровня
- Вновь становится зеленым, или если преодолевает заданное значение +75 футов в Go-around,  или при тачдауне (20.5=1.000), или при нажатии RST на EFIS.

если RADIO, то
- Отображается над тоже под авиагоризонтом, значение в футах радиовысоты, адрес 20.4
- Исчезает, если задана высота ниже 0 футов
- Становится желтым и моргает 3 сек, если судно снижается ниже заданного значения
- Вновь становится зеленым, или если преодолевает заданное значение +75 футов в Go-around,  или при тачдауне (20.5=1.000), или при нажатии RST на EFIS.

Если все верно, то буду реализовывать

**Comment by soitanen** [comment]
В принципе аналитика верная. Еще хорошо написано в АММ, документ 31.pdf (я тебе вроде открывал доступ через Гугл.Диск). Старница 361-362 про БАРО, стр 378 про РАДИО. Плюс от пилота - если держим больше 2-х секунд, то прибавляем не по одному футу, а по 10. Если еще 3 секунды - по 100.

**Comment by soitanen** [comment]
Еще предлагаю сделать, что после реинициализации minimums автоматом сбрасывается на RADIO 200 - это удобно. если надо - меняем. не надо - примерно соответствует действительности при заходе по ИЛС.

**Comment by ponemetski** [comment]
можно проверять 

сделал
- ускорение если держать ручку долго
- остальную логику моргания желтым

**Comment by soitanen** [comment]
вроде бы ок
