### ISSUE TITLE
высота от земли желтая и белая полоска

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#91]
На ПФД на шкале высоты должна рисоваться индикация высоты земли. она берется как landing elevation. значение - берется из CDU, точнее из базы данных аэропортов. На взлете рисуется высота аэродрома взлета, на посадке - логично что ап посадки, переключение судя по документам происходит на середине полета по маршруту. От этой высоты вверх по шкале ползет желто-белая линия (400 желтая, 400 белая)

**Comment by ponemetski** [comment]
в fcom
<img width="401" alt="screen shot 2018-11-21 at 23 56 59" src="https://user-images.githubusercontent.com/1931079/48867996-29d83c00-ede9-11e8-9de9-167031304291.png">

делаем 500?

**Comment by ponemetski** [comment]
стою в ULLI где возвышение 79 футов над уровнем баренцева моря 
давление 29.92
по данным из иксплейна самолет находится на высоте 9 футов над уровнем баренцева моря 

<img width="895" alt="screen shot 2018-11-22 at 00 45 47" src="https://user-images.githubusercontent.com/1931079/48869948-12e91800-edf0-11e8-95f0-a9e5ff6caf69.png">

не понятно почему уровень полосы выше чем мы стоим 
и как посчитать правильно

**Comment by ponemetski** [comment]
готово,

проверял на KSEA, все равно на 30 футов отличается высота торца полосы по навдате от той которая из иксплейна приходит

**Comment by soitanen** [comment]
в КСЕА террейн кривой, поэтому может быть ошибка. в москве, новосибирске - ок, так что ок
