### ISSUE TITLE
Зеленые метки на шкале двигателей

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#92]
Должны соответствовать текущему лимиту тяги. Плюс нужен правильный расчет взлетного лимита в CDU на странице N1 LIMIT.
Вспоминаю, что вроде этот баг я уже писал, даже с картинкой этих багов.

**Comment by ponemetski** [comment]
Баг #10, поставил на него тэг критикал лоу, и закрыл этот баг
