### ISSUE TITLE
Engine anti-ice

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#94]
Включение engine anti-ice должно приводить к появлению зеленой индикации TAI на upper EICAS. Кроме того, если он включен, а значение TAT (total air temperature) больше +10 градусов, то на CDU должно появитсяь сообщение TAT ABOVE +10C

**Comment by ponemetski** [comment]
> Включение engine anti-ice должно приводить к появлению зеленой индикации TAI на upper EICAS. 

должно работать
вторую часть - чиню

**Comment by soitanen** [comment]
TAI не появляется. Сообщение появляется.

**Comment by ponemetski** [comment]
поправил TAI

**Comment by soitanen** [comment]
ок
