### ISSUE TITLE
Fuel flow

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#97]
реализовать работу тумблера fuel flow (просмотр израсходованного и сброс)

**Comment by ponemetski** [comment]
> Тумблер FUEL FLOW На панели №40.
Положение RATE, фиксированное - стандартное отображение
Положение USED, автовозвратное - 10 сек показывает расход с момента последнего сброса в рамке FF на LOWER и UPPER EICAS, затем возвращает стандартное отображение. Расход отображается в фунтах (килограммах) в час х 1000. То есть, число 5.26 будет значить, что с момента последнего сброса жгли по 5260 фунтов(кг) в час.
То есть, в момент нажатия RESET надо запомнить кол-во топлива в обоих баках, а при нажатии на USED, вычислить разницу между старым значением и новым, поделить эту разницу на кол-во прошедшего времени в часах, разделить полученное значение на 1000, округлить до сотых и показать.
Положение RESET, автовозвратное - собственно, сброс. Показывает расход с момента последнего сброса, затем отображает значение 0.0, и возвращается к стандартному отображению.

**Comment by ponemetski** [comment]
готово, но считает по общему объему сожженного топлива, то есть если лететь на одном двигателе и поставить USED то показывает не адекватно

**Comment by soitanen** [comment]
перемудрил ты тут. USED - это тупо сколько сожжено топлива с последнего ресета, а не средний за последний час. Т.е. когда ресет (или при первичной инициализации), то дальше просто интегрируем по каждому двигателю его расход. Особой точности тут не надо, можно раз в секунду мгновенный расход брать и по 1 секунде и интегрировать.

**Comment by ponemetski** [comment]
поправил, можно проверять и закрывать

**Comment by ponemetski** [comment]
> поднимаем ресет. если сразу отпустили, то ничего и не произойдет. А пока держим, то первую секунду горит юзед, затем в течении 1-2 секунд сматывается к 0, причем должно быть именно видно уменьшение, чтобы понимать, что ты ресетишь. отпустил - и все, интегрируется занвоо

**Comment by soitanen** [comment]
да, теперь как надо
