### ISSUE TITLE
сигнализация glideslope

### ISSUE THREAD

**Issue by soitanen** [ponemetski/extrinofms-issues#99]
режим мягкий-жесткий оставляем, а вот начнет орать или показывать желтую лампочку только если режим по pitch = GS И высота по РВ > 50 ft

**Comment by ponemetski** [comment]
```c#
bool norm = false;
bool loud = false;

// добавил radioAlt > 50.0
if (radioAlt > 50.0 && radioAlt < 1000.0 &&
    ((type1 == 6 || type1 == 10) && gs1 < -1.5 && 100 * -gs1 + radioAlt - 250 > 0) ||
    ((type2 == 6 || type2 == 10) && gs2 < -1.5 && 100 * -gs2 + radioAlt - 250 > 0))
{
    norm = true;

    if (radioAlt < 300.0 &&
        ((type1 == 6 || type1 == 10) && gs1 < -2.0 && 100 * -gs1 + 1.5 * radioAlt - 350 > 0) ||
        ((type2 == 6 || type2 == 10) && gs2 < -2.0 && 100 * -gs2 + 1.5 * radioAlt - 350 > 0))
    {
        loud = true;
    }
}
```

**Comment by ponemetski** [comment]
364 Glideslope.wav
Сигнализация армируется ниже 1000 футов радиовысоты с выпущенными закрылками. Играет при полете ниже глиссады ILS, отключается нажатием Below G/S P-ihnibit на радиовысоте ниже 1000 футов. Сама кнопка горит во время сигнализации.
Первая сработка - в полтона, если не устранить кривой движ - играет на полную громкость и быстрее (чаще). Нужно делать разные промежутки между проигрываниями и чтобы звуки не накладывались.
Ниже график зависимости сработки в зависимости от радиовысоты и отклонения от глиссады, в точках указателя девиации, мы это умеем уже. На графике представлена сработка в полтона и сработка в полную громкость.

**Comment by soitanen** [comment]
Вот тут тоже проблема в том, что орет выше 1000

пн, 10 сент. 2018 г., 16:01 ponemetski <notifications@github.com>:

**Comment by soitanen** [comment]
Перечитал кое-какие документы, то что я выше написал про режим по тангажу=глиссада - неправда, реализовывать не надо. А вот условие начала сигнализации это не полторы точки, а 1.3 точки.

**Comment by ponemetski** [comment]
поправил на 1.3 точки, можно закрывать

**Comment by soitanen** [comment]
Ок
